### ISSUE TITLE
 App crashes when opening website categories in settings

### ISSUE THREAD

**Issue by sarathms** [ooni/probe#1018]
## Expected Behavior
Opens the screen that allows (un)selecting website categories.

## Actual Behavior
Crashes

## Steps to Reproduce the Problem

  1. Open app and go to settings tab
  2. Open 'Test Options' -> 'Websites'
  3. Tap on 'Website categories to test'

## Specifications

  - Version: 2.3.0-beta.1
  - Platform: Android 9

Crash report was also sent from the app.

**Comment by lorenzoPrimi** [comment]
Error found, now I need to understand how to fix it
```
org.openobservatory.ooniprobe E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.openobservatory.ooniprobe, PID: 3158
    java.lang.IllegalArgumentException: Must use non-zero containerViewId
        at androidx.fragment.app.FragmentTransaction.replace(FragmentTransaction.java:223)
        at androidx.fragment.app.FragmentTransaction.replace(FragmentTransaction.java:200)
        at localhost.toolkit.preference.ExtendedPreferenceFragment.onPreferenceStartScreen(ExtendedPreferenceFragment.java:37)
        at org.openobservatory.ooniprobe.fragment.PreferenceFragment.onPreferenceStartScreen(PreferenceFragment.java:109)
```

**Comment by lorenzoPrimi** [comment]
So far I struggled to find a way to make this work, this is because of the duplication of the setting screen. 
Now I see two solutions:
- If we plan to remove the setting icon from the test overview screen I can duplicate the settings .xml files and when we decide to remove if from that screen I simply remove the duplicated code
- If we are not sure we will remove that setting icon I'd have to find a fix to don't have duplicated code (xml)

note to ME: maybe try this https://stackoverflow.com/questions/53639787/implementing-preferencefragmentcompat-inside-preferencefragmentcompat

**Comment by lorenzoPrimi** [comment]
This is blocked by the decision on #1024

**Comment by hellais** [comment]
I replied to #1024. This should not be blocking anymore.
