### ISSUE TITLE
The test options should not be duplicated

### ISSUE THREAD

**Issue by hellais** [ooni/probe#1024]
In the testing version of 2.3.0, the test options are duplicated both inside of the test card and the global settings.

The desired behaviour should be that when you tap on the gear icon inside of the test card, the user is redirected to the global app settings, rather than accessing a duplicate setting.

In practice what this means is that if the users taps on the back button in the upper right corner, they should end up in the test options pane of the global settings and not back in the settings card.

This affects both Android and iOS app versions.

**Comment by lorenzoPrimi** [comment]
There is no way to access a subscreen to the setting page. 
Either you access the settings (home page) but that is not what we want or we remove the secondary access.

**Comment by hellais** [comment]
>There is no way to access a subscreen to the setting page.

Why is this the case?
I found this on the Android developer docs, could it be related:
https://developer.android.com/guide/navigation/navigation-navigate

?

**Comment by lorenzoPrimi** [comment]
Because in Android we use the standard component for Preferences
https://github.com/ooni/probe-android/blob/master/app/src/main/res/xml/preferences_global.xml

I mean there is a way to access the subpage like we do now, but not to keep the stack. So back would bring you back to the previous page, not to the general setting page.

**Comment by hellais** [comment]
Ok I see. Then I suggest we just remove the settings gear and just keep it inside of the global settings.
