### ISSUE TITLE
Fix formatting of figures under Data Usage

### ISSUE THREAD

**Issue by agrabeli** [ooni/probe#1045]
![data-usage](https://user-images.githubusercontent.com/8290574/76631139-75b07680-6541-11ea-8bfc-6f1625a93b4c.png)

Perhaps the figures under "Data Usage" should have the same size as the figures under "Network" and "Tests"? The formatting currently looks inconsistent.

**Comment by hellais** [comment]
I commented also on the PR: https://github.com/ooni/probe-desktop/pull/114#issuecomment-601661687.

But I think we should preserve the current hierarchy of elements giving equal important to each column. In order to achieve that, the font size of the data usage values needs to be adjust accordingly.

I believe the only real issue with this view is that the Data Usage column values are not vertically aligned with the rest, but the size is correct and consistent with the mobile version.

See:
![Screenshot_20200320-125142](https://user-images.githubusercontent.com/424620/77161479-0b9c5200-6aaa-11ea-8225-a71f3c5bdf0c.png)
