### ISSUE TITLE
Add end to end tests to OONI Probe Desktop

### ISSUE THREAD

**Issue by hellais** [ooni/probe#1062]
Currently we don't have any tests in OONI Probe Desktop. We should add some basic testing of it prior to launch.

**Comment by sarathms** [comment]
Turns out Cypress doesn't have a stable support for testing electron apps yet. There is an alpha stage plugin that seems to work to some extent.
https://www.cypress.io/blog/2019/09/26/testing-electron-js-applications-using-cypress-alpha-release/
https://github.com/cypress-io/cypress/issues/4964
https://github.com/cypress-io/cypress-electron-plugin

However, electron project itself develops an end-to-end testing tool called [`Spectron`](https://github.com/electron-userland/spectron)
And then there is [`TestCafe`](https://devexpress.github.io/testcafe/).

I need to sit down and do a usability study of the available options. Factors:
