### ISSUE TITLE
Ensure the measurement times are displayed in the local system timezone

### ISSUE THREAD

**Issue by agrabeli** [ooni/probe#1099]
Currently the timezone is not displayed in the test results of the OONI Probe desktop app, making it confusing to determine if the test time pertains to UTC or some other timezone.

I therefore propose that "UTC" (assuming that the timestamps are in UTC) is added to the main test results page, in addition to the individual measurement pages.

Below I share screenshots to show the type of result pages that I am referring to.

![main-results](https://user-images.githubusercontent.com/8290574/79216039-cc64e500-7e4c-11ea-9e17-d69caffc21c7.png)

![measurement-page](https://user-images.githubusercontent.com/8290574/79216015-c3741380-7e4c-11ea-908e-19ca2a27ef11.png)

**Comment by hellais** [comment]
I think we probably want the measurement timestamps to be in the local timezone of the user, otherwise if, for example, they don't know what UTC is they are going to be very confused as to why the measurements are indicated at a different time.

If we are displaying the in the system time, we probably don't have to add an indication next to it as to the timezone of it.

@sarathms can you confirm if we are resolving the timestamps in the system timezone?

**Comment by sarathms** [comment]
Yes we are showing the system timezone except for the measurement pages where for some reason I made it UTC explicitly. I am changing it now to make it consistent with the test results screens.
