### ISSUE TITLE
Reduce surprise of users running the websites test on desktop

### ISSUE THREAD

**Issue by agrabeli** [ooni/probe#1117]
Feedback from a community member:

> When running the websites test, it is not made immediately clear that the test will run for all of the test lists. The test lasts hours, which, compared to the android app experience, where you can pick how long you want to test for, it is a bit unexpected and overwhelming. Maybe you could make this clearer, and perhaps add an option to select how many tests to do or for how long, or communicate to the user that it is okay to stop the test midway (and that all results so far will be submitted normally).

**Comment by agrabeli** [comment]
Perhaps when the user clicks "Run" (on the Websites card), a window could pop-up saying something in the lines of:

> You are about to test more than 1,000 websites, which could potentially take hours (you can stop the testing anytime, and your results will still be saved and published). How would you like to proceed?
> 
> - That's fine by me! Test all the websites
> 
> - Only perform testing for ___ minutes.

**Comment by pappasadrian** [comment]
Hello, 
I gave that original feedback. I agree with agrabeli's suggested approach. I'd add to it that the user's selection could be saved as a setting (so the user would only be asked this the first time and not every time), and then they could change their selection in the settings. 

So I imagine a dialogue, as described by agrabeli, perhaps with a sidenote that this option will be saved and can be changed again in the settings.

It might also worth noting approximately how much bandwidth/data intensive the test is. This would be especially helpful for metered connections.

**Comment by hellais** [comment]
I like this idea!

That said, I think this dialogue need a little bit more thought and research especially thinking about how it's going to work when we add the "Run all tests" button to desktop as well.

I would say that if we expect users to be surprised that the test is going to run for so long, then we should rather change the default to not make them so much surprised.

We can investigate the level of surprise users might have by looking at the runtime of tests collected from desktop probes and understand after how long users will terminate the test (i.e. how much patience they have).

Other solution to this problem which we could think about include:
- Starting the test, but then showing in the running test screen a message telling them that they can cancel the test at any time by clicking on the X
- Adding support for running tests in the background of the app, so that the user can continue using OONI Probe and viewing their results as the test is running
- Adjusting the default maximum tested URL size to something more reasonable

I think we should investigate these option and then pick one which we think is going to work best.

For the time being I suggest we push this back to a future milestone as this needs a bit more fleshing out before it's ready for implementation.

**Comment by sarathms** [comment]
We need to think about controlling the number of URLs tested from the backend.

**Comment by hellais** [comment]
We also said to implement, similar to on mobile, a limit which is based on time, for example 90 seconds, after which the desktop app kills the process. Let's discuss this with @FedericoCeratto too and for the moment keep things as-is.

**Comment by hellais** [comment]
We now apply a limit to the maximum runtime of user initiated tests on OONI Probe desktop, similarly to how we do it on mobile. I think we can consider this issue closed.
