### ISSUE TITLE
languages are not supported in the stable version

### ISSUE THREAD

**Issue by eduardoaddad** [ooni/probe#1133]
languages are not supported in the stable version

![Anotação 2020-05-04 105625](https://user-images.githubusercontent.com/16819380/80973597-faa76600-8df5-11ea-8461-53ae4912a979.png)
![Anotação 2020-05-04 105625e](https://user-images.githubusercontent.com/16819380/80973601-fb3ffc80-8df5-11ea-8aeb-a4553e5174c7.png)

**Comment by hellais** [comment]
Thanks for reporting this!

Yes this looks like a bug. It might be because the language code we use for Portuguese is `pt_BR` 
 (https://www.transifex.com/otf/ooniprobe/language/pt_BR/) and it's not matching the code `pt`.

While fixing this bug we should also check to be sure that we don't state that the "Current app language" is a language which is not supported. For example if the user has their OS set to amharic, but we don't support that in OONI Probe it should say in this page "Current app language: en".

cc @sarathms

**Comment by sarathms** [comment]
> we should also check to be sure that we don't state that the "Current app language" is a language which is not supported.

The way it was written, `settings.js` page picks up the locale from `react-intl` context, which gets initialized after we check for language support and the `en` fallback. I will check what went wrong then.

**Comment by eduaddad** [comment]
The error continues in version 3.0.3

**Comment by sarathms** [comment]
This was addressed in https://github.com/ooni/probe-desktop/pull/164 and will be rolled out in the next release.
