### ISSUE TITLE
Ask user to share app usage

### ISSUE THREAD

**Issue by lorenzoPrimi** [ooni/probe#1211]
![83F04015-BD28-4312-9EE7-A4791884BD96.png](https://images.zenhubusercontent.com/589f552b51aa2c3057742305/0d01f4fe-32d5-4f16-853c-b616b6937fe0)

**Comment by lorenzoPrimi** [comment]
the new `Collect app usage statistics` and `Send crash` setting are going into `Advanced` or we create a new `Privacy` menu item?
@hellais @agrabeli

**Comment by agrabeli** [comment]
Thanks @hellais, your suggestions sound great.

**Comment by agrabeli** [comment]
> So I think that in order to implement this we should do the following:
> 
> **For existing app users**
> 
> When the run the app after the update (the logic can actually be, if the setting is off, show it once), we display a modal that says:
> 
> Title: Help us improve OONI Probe
> Description:
> We would like to collect some metrics about how the app is used so we can make it better. We will never link these app metrics to your identity and you can find all the metrics which we send in the open source code repositories: https://github.com/ooni/probe.
> You may opt-out of this at any time.
> `[Share app usage]` `[Don't share]`
> 
> @agrabeli perhaps you can help polishing this copy a little bit

The title is good. 

I would recommend replacing the description with the following edited version:

We would like to collect some metrics about how you use OONI Probe so that we can improve it. We will never link these app usage metrics to your identity. You can opt out of this at any time through the settings.

 `[Share app usage]` `[Don't share]`

@hellais it's unclear to me what information specifically the user can find through the OONI Probe github repository (with respect to app usage metrics). Can you please elaborate?

@hellais @lorenzoPrimi How will they be able to opt out? Through the settings? (i.e. is this being added to the settings?)

> 
> **For new users**
> 
> As part of the onboarding process we should add a bullet point on the last step which mentions that we will by default collect app usage and crash reports.
> 
> I think it's worth considering to consolidate the bullets in the last step of the onboarding with another section beyond the _We collect and publish_.
> 
> My suggestion is:
> 
> Default Settings
> 
> We collect and publish:
> 
> * Country code (e.g. IT for Italy) & Network information (including Autonomous System Number)
> * Time & date of testing
> * We do our best not to publish your IP address or any other potentially personally-identifiable information.
> 
> To improve our app we collect:
> 
> * Crash reports
> * App usages
> 
> Learn more through [OONI's Data Policy](https://ooni.io/about/data-policy/).
> 
> Input from @agrabeli on the copy here is also welcome!

@hellais overall, your suggestion sounds good!

I would suggest suggest minor copy edits so that it reads as follows:

We collect and publish:

* Country code (e.g. IT for Italy)
* Network information (including Autonomous System Number)
* Time & date of testing
* We do our best not to publish your IP address or any other potentially personally-identifiable information

To improve OONI Probe we collect:

* Crash reports
* App usage metrics

^^ @hellais I propose keeping network information on a separate line than country code, because in the app it will likely end up being incredibly long and create UX problems.

@lorenzoPrimi If you think my proposed copy edits are reasonable, let's coordinate on creating strings for them.

**Comment by lorenzoPrimi** [comment]
@agrabeli for the setting there will be a new one called
`Settings.Advanced.CollectAnalytics` 
with string
`Collect app usage statistics`

**Comment by agrabeli** [comment]
@lorenzoPrimi the copy for the latter should be "Share app usage metrics".

**Comment by lorenzoPrimi** [comment]
Edited.
Closing this screen as it has been implemented.
