### ISSUE TITLE
Evaluate adding privacy tab or not

### ISSUE THREAD

**Issue by hellais** [ooni/probe#1217]
Came from: https://github.com/ooni/probe/issues/1182#issuecomment-650121758

**Comment by agrabeli** [comment]
@lorenzoPrimi @hellais I think it makes sense to have a Privacy tab, so that it's potentially clearer to users that that's where they have to go in order to opt out of things like analytics (also, "Advanced" may sound overwhelming and many users may not tap it at all). However, would the Privacy tab only include "app usage statistics" or are there also other settings (related to opt out) that would go there?

**Comment by lorenzoPrimi** [comment]
@agrabeli I totally agree with you.
In this case we would have:

Privacy :
- Share app usage
- Send crash report

Advanced:
- Debug logs

**Comment by agrabeli** [comment]
@lorenzoPrimi sounds good. 

Speaking of settings, how is the "send email to support" option actionable/useful? Do we want to consider removing it?

In almost all cases, it seems that users send us empty emails without any actionable information. Furthermore, we don't really have the in-house resources to follow-up with every single empty email that we receive.

**Comment by lorenzoPrimi** [comment]
That function has to be totally restructured. My advice is to remove the email client and use a form. 
I filled an issue: https://github.com/ooni/probe/issues/1227

Back on the topic of privacy tab settings, what do you think @hellais?

**Comment by hellais** [comment]
Yeah I agree with the fact that we should have a privacy tab.

**Comment by lorenzoPrimi** [comment]
We need an icon for that.
I'll take care of strings

**Comment by hellais** [comment]
> We need an icon for that.

Can you open another issue for that and assign it to me to work on in Sprint 19?

Thanks!

**Comment by lorenzoPrimi** [comment]
UX issue https://github.com/ooni/probe/issues/1229
Implementation issue https://github.com/ooni/probe/issues/1230
