### ISSUE TITLE
Restructure Sharing section in App Preferences

### ISSUE THREAD

**Issue by lorenzoPrimi** [ooni/probe#1260]
Removing include_{asn,cc,ip} settings https://github.com/ooni/probe-engine/issues/974
will require removing the relative settings from the app.
In this case the `Sharing` section will start to be empty with only `Automatically Publish Results` and `Manual Result Upload`
We need to discuss if move these two into the `Privacy` section or restructure them in another way

After this issue will be closed we need to update the app policy and onboarding.

**Comment by hellais** [comment]
My suggestion for this would be to:
• Consolidate "Automatically Publish results" & "Manual Result Upload" into a single options (at this point it's been around a while that we don't have to worry about the bug anymore). This means always offering the option to Upload un-uploaded measurements.
• Move all the Sharing settings under the Privacy tab
• Drop the ability to include the IP address
• Drop the ability to opt-out of Include Network info

**Comment by lorenzoPrimi** [comment]
This has been discussed and will be implemented in spring 26.

@agrabeli How would you rename "Automatically Publish results"?
We thought about a more generic "Publish results"

**Comment by agrabeli** [comment]
@lorenzoPrimi @hellais thanks for your input! Here are my thoughts:

1. I agree that **Publish results** is better than "Automatically publish results"

2. I agree about dropping the settings to opt-out of ASN and opt-in to IP address collection (since not having ASN makes measurements non-actionable, while the risk associated with IP address collection is greater than the benefit of its collection)

3. Rather than moving the remaining "Publish results" option under the Privacy tab, I would prefer to see it **kept under the Sharing tab** because:

* If moved under the Privacy tab, it may inevitably communicate to users that there's some privacy risk associated with publishing results (which is not true) -- and this may risk dis-encouraging users from publishing their test results

* We might add further sharing options in the future, and keeping the tab (even if it only has 1 option currently) is probably better than removing it and having to re-add it in the future

**Comment by lorenzoPrimi** [comment]
@sarathms I'm going to edit "Automatically publish results" in "Publish results" just FYI.
"Include Network Info" and "Include my IP address" won't be removed from the spreadsheet for now

**Comment by hellais** [comment]
We agreed with @agrabeli to go for putting it inside of Privacy since it does indeed relate to privacy.
