### ISSUE TITLE
mobile: release 2.7.1

### ISSUE THREAD

**Issue by lorenzoPrimi** [ooni/probe#1265]
- Update probe-engine to v0.20.1 
- Restructure sharing settings
- minor fixes and improvements (Adding loader on test deletion)

**Comment by agrabeli** [comment]
@lorenzoPrimi You could use the following release notes:

# What's new?

* Removed the "Include Network Info" setting in order to collect ASNs by default (as ASN information is necessary)
* Removed the "Include my IP address" setting (to ensure greater protections for users)
* Restructured the Sharing settings
* Probe engine updated to v0.20.1
* Minor fixes and improvements (added loader on test deletion)

@lorenzoPrimi Is the Sharing setting still included in this release? Or has it been removed (and its settings have been moved under the Privacy tab)? Please clarify this point before releasing (as I may need to edit the above release notes). Thanks.

**Comment by lorenzoPrimi** [comment]
It has been removed and merged. I will change 
- Restructured the Sharing settings
in
- Merged Sharing settings into Privacy tab

**Comment by agrabeli** [comment]
@lorenzoPrimi Thanks for the clarification. Please use these release notes:

# What's new?

* Removed the "Include Network Info" setting in order to collect ASNs by default (as ASN information is necessary)
* Removed the "Include my IP address" setting (to ensure greater protections for users)
* Removed the Sharing section, and moved "Publish results" under the Privacy settings
* Probe engine updated to v0.20.1
* Minor fixes and improvements (added loader on test deletion)
