### ISSUE TITLE
Add support for registering launchd service in probe-cli

### ISSUE THREAD

**Issue by hellais** [ooni/probe#1312]
This is about implementing the needed features for setting up a periodic task for running experiments in probe-cli.

It's a requirement to: https://github.com/ooni/probe/issues/1289

**Comment by bassosimone** [comment]
@hellais my understanding is that we're not adding this support to ooni/probe-cli, but rather we're adding support for running in the background as part of ooni/probe-desktop. As such, I am going to close this issue as WontFix. If closing this issue is not the desired outcome, and we perhaps want to keep this in the radar, please reopen the issue again.
