### ISSUE TITLE
Scrub Probe IP from GET request

### ISSUE THREAD

**Issue by anadahz** [ooni/probe#1322]
## Expected Behavior

The probe IP should be redacted from the GET request.

## Actual Behavior

The probe IP is not redacted from the GET request.

## Steps to Reproduce the Problem

  1. Run a test with a location header that includes probe's IP

## Specifications

- Platform: ios
- Software Name: ooniprobe-ios (2.3.0)
- Measurement Engine: libmeasurement_kit (0.10.11)

---

_In order to protect from unintentional PII disclosure, an email will be sent to team@oo with an example measurement of the aforementioned issue._

**Comment by bassosimone** [comment]
Thank you for researching this topic and for contacting us in private!

I have spent some time looking into the data you provided us and determined that his issue is MK only.

I am confident about that diagnosis because Probe Engine does the following:

1. [MeasureWithContext calls Scrub](https://github.com/ooni/probe-engine/blob/a64674fd312099f4824702c851b4c16bc5582a9c/experiment.go#L116)

2. [Scrub calls MaybeRewriteTestKeys](https://github.com/ooni/probe-engine/blob/5862a9041c5d8d4975ce41150096fcc7e2c3d772/model/scrub.go#L15)

3. [MaybeRewriteTestKeys removes the bytes corresponding to the user's IP from the whole JSON](https://github.com/ooni/probe-engine/blob/5862a9041c5d8d4975ce41150096fcc7e2c3d772/model/scrub.go#L27)

4. BTW, we also have [a test checking that we are scrubbing the whole JSON](https://github.com/ooni/probe-engine/blob/5862a9041c5d8d4975ce41150096fcc7e2c3d772/model/model_test.go#L100).

Therefore, I am going to move this issue into the MK repository.

Please, let us know if you encounter similar issues with a Probe-Engine-based version of OONI.

**Comment by bassosimone** [comment]
Moved here: https://github.com/measurement-kit/measurement-kit/issues/1935.
