### ISSUE TITLE
Add new "Social media websites" card in OONI Probe apps

### ISSUE THREAD

**Issue by agrabeli** [ooni/probe#1412]
# Problem

Social media websites are frequently blocked around the world. In fact, social media websites are probably the type of websites that get blocked the most worldwide. We therefore need ongoing testing of social media websites, particularly in response to reports of social media blocking (which are frequent). 

However, most OONI Probe users don't end up testing social media websites frequently, because they're often not included in the URLs that are randomly tested (in 90 seconds) when they tap "Run" in the OONI Probe mobile app (which accounts for most users worldwide). And coordinating social media testing through OONI Run links can be tedious and confusing/challenging for users, often not leading to the collection of desired measurements. We include a "social media" OONI Run button on the OONI website (https://ooni.org/get-involved/run), but getting users to use that has been challenging too. 

As a result, getting social media websites tested during blocking events (and having them tested regularly) is an ongoing challenge.   

# Proposed solution

To ensure the more regular and easy testing of internationally-relevant social media websites, I propose that we **add a new "Social media websites" card** in the OONI Probe apps.

This card could be positioned **right after the "Websites" card**, and right before the "Instant Messaging" card.

Upon running this "Social media websites" card, users would test a list of internationally-relevant social media websites (such as those included in this "social media" button: https://ooni.org/get-involved/run). 

This list could be hosted on github (to enable public review and contributions), potentially in the Citizen Lab test list repository. 

By adding this card, most users would end up testing social media websites regularly every time they tap the canonical "Run" button in the app (which runs all tests). Essentially, social media websites would be included in the default testing that most OONI Probe users perform. :)

What do you think?

**Comment by hellais** [comment]
My proposal for how we could go about implementing this is that we have the logic for the Social media website cards wired to making a query to the test-lists API endpoint (or check-in API) by querying the global list for the `GRP` category code (https://api.ooni.io/api/v1/test-list/urls?country_code=XX&category_codes=GRP).
This is then used as an input list to the test which will return the results similarly to how we do it for the websites card.

Before doing this we should also do a bit of a cleanup of the citizenlab global test list by removing dead social media from it and ensuring that all the URLs with that category code are properly categorised.

**Comment by hellais** [comment]
Alternatively @agrabeli was suggesting we consolidate the social media testing together with the IM app tests in a single card which is called "Social media and IM Apps". I expect this however to be considerably more hard to do as we would have to alter the logic for running tests to consider running both the IM test group together with a set of URLs/websites.

I would like to know from @bassosimone @sarathms and @lorenzoPrimi what your thoughts are about these two approaches and what you believe the effort estimate for each of these solutions to be.

**Comment by agrabeli** [comment]
Given that integrating social media websites with the IM apps will make the app UI much more complicated (since we would have to display individual website rows + IM app results), perhaps we can go with the 1st option that @hellais suggested:

Creating a **new Social media websites card** which will only run the `GRP` websites from the Global test list.

That's probably the easiest and cleanest way to do this. I agree that we'll first have to clean-up the `GRP` URLs from the Global test list.

**Comment by lorenzoPrimi** [comment]
The solution to test IM apps together with IM websites is doable, but will produce two different results items.

The first solution I'm not sure I'd integrate in the dashboard as every card is a different test suite, tapping on it it would show more or less the same Websites Overview card. Maybe can be a button inside the websites overview, where "choose websites" is?

**Comment by hellais** [comment]
If it's not too much effort to do it inside of the IM apps card, then I think that would be the preferable option. I don't think we want to have another button inside of the websites card itself as we have seen that the discoverability of these options is already not so great.

We might eventually add an additional step to the choose websites workflow where instead of choosing an individual URL they can select a category code, making it a generic version of this, but that I think deserves it's own separate issue.

**Comment by lorenzoPrimi** [comment]
As long as we don't confuse the user when they tap something inside the IM card and get a result of type website for me it's ok.

We can also add it to the dashboard but that would confuse some users as well

**Comment by sarathms** [comment]
If we are going to word it as "Social Media Websites", then I would prefer bringing it under "Websites" card. It involves some UX problem-solving exercise around feature discoverability and the hierarchy of actionable UI elements,  doing which is useful beyond the scope this issue itself.

I am not in favor of option 2. because I feel mixing up testing of IM apps and a few websites can be potentially confusing to users, as @lorenzoPrimi suspects. Maybe I would change my mind if we look at some rough sketches of how we display the results to the user. Running the tests itself this way is not a problem. It is very close to how we already run all the test groups.

**Comment by sarathms** [comment]
Considering IM tests are essentially a custom set of `web_connectivity` tests, I am wondering if we can allow probes to build such, er.. _decks_ :open_mouth: for the purpose of showing result on the probe, but submit them as `web_connectivity` measurements. I know this doesn't help with sharing an OONI Explorer link which says definitively that "MySpace social media" is blocked. But options 1 and 2 above also basically won't let that happen anyway.

**Comment by bassosimone** [comment]
It's a complex topic. If I am a user and configure in websites that I don't want to test for social media websites but then I tap "run all" and somehow the app is testing the social media websites, is this honoring my original preferences? The answer is a bit gray here because, on the one hand, I tapped "all" but, on the other hand, I also said I didn't want to test social media.

I suppose we should discuss this topic more. I am currently not sold about any of the proposed solutions and I am wondering whether instead we could find a different solution for the original problem. (Maybe it's a stupid suggestion, but we control the API and we control URL prioritization, so we can ~easily find a way so that many users test social media w/o changing the apps.)

**Comment by hellais** [comment]
We discussed this during the backend meeting and we came to the conclusion that it appears that we would rather prioritise, where needed, the testing of social media URLs directly in the backend, rather than having to rely on users tapping on a specific card for that.

As time goes by we are going to be reliant more and more on automatic runs and less from measurements coming from user initiated tests, so this is in line with that direction.

@agrabeli what do you think of this? Can we perhaps close this issue?

**Comment by hellais** [comment]
We said we would be discussing this further in a meeting. Adding the relevant label and adding it to the frontend meeting agenda.

**Comment by hellais** [comment]
@agrabeli is going share a list of GRP sites to prioritise and @FedericoCeratto will prioritise them.

**Comment by agrabeli** [comment]
@FedericoCeratto I have shared the social media URLs for top prioritization in this ticket: https://github.com/ooni/backend/issues/507

**Comment by hellais** [comment]
This can be closed.
