### ISSUE TITLE
Don't run automated test when a VPN is enabled

### ISSUE THREAD

**Issue by lorenzoPrimi** [ooni/probe#1460]
Found out by @xhdix

**Comment by agrabeli** [comment]
@lorenzoPrimi Perhaps we can somehow communicate to users that the reason why tests are not run automatically is because we detected that they have a VPN enabled? Otherwise there's the risk that users may think that automated testing doesn't work, if they don't ever see it running and don't know that they're supposed to disable their VPN is order for it to work. 

Perhaps we can have a pop-up modal (perhaps triggered when they enable automated testing, but have a VPN enabled)? If so, I'd be happy to write the relevant copy.

**Comment by lorenzoPrimi** [comment]
@agrabeli I would add this info in the footer inside the automated testing setting screen.
Adding a sentence like "The tests won't run if you have a VPN enabled at the moment of testing because ..."
I don't think it's ideal to do it when the test fails to run, expecially if we implement something backend side as well

**Comment by xhdix** [comment]
I think to prevent false positive results, active tests should also be stopped if a VPN is activated in the middle of the test.

**Comment by lorenzoPrimi** [comment]
So for this ticket I will 
- [ ] Add a sentence in the footer explaining VPN should not be active when automated test is running
- [ ] `return` the run test function in case a VPN is active in that moment

**Comment by xhdix** [comment]
@lorenzoPrimi it's not like that in `ooniprobe-android (3.0.0-beta.1)`

A list of sites that are blocked in Iran:
![image](https://user-images.githubusercontent.com/12384263/117729029-e9581d00-b1f2-11eb-9f86-d4e7af7b5403.png)

DNS = 10.10.34.36 :
https://explorer.ooni.org/measurement/20210510T214741Z_webconnectivity_AE_197207_n1_93qHoh6orjVcZeln?input=https%3A%2F%2Ffacebook.com%2F
![image](https://user-images.githubusercontent.com/12384263/117729224-363bf380-b1f3-11eb-9e6d-c20f8a9539b9.png)

After activating a VPN when this test was running (have a same ID) :
https://explorer.ooni.org/measurement/20210510T214741Z_webconnectivity_AE_197207_n1_93qHoh6orjVcZeln?input=https%3A%2F%2Ftelegram.org
![image](https://user-images.githubusercontent.com/12384263/117729354-62577480-b1f3-11eb-9c99-bb8289fafda4.png)

It doesn't seem to detect network changes well. (only detected by engine)

Of course, in mobile internet, momentary internet interruption can happen a lot.

**Comment by lorenzoPrimi** [comment]
@xhdix this hasn't been implemented yet. you can check the progress here https://github.com/ooni/probe/issues/1460
