### ISSUE TITLE
WhatsApp measurements inaccurately display that WhatsApp Web is "likely blocked" in Cote d'Ivoire

### ISSUE THREAD

**Issue by agrabeli** [ooni/probe#1576]
A community member in Cote d'Ivoire reported that when they run the IM tests, the WhatsApp test results say that "WhatsApp Web is likely blocked", even though WhatsApp Web works in that country. They mentioned that this has been an issue in many OONI Probe Mobile versions (way before 2.7.0). 

It sounds like it may be a bug or a limitation to our WhatsApp test methodology. It's unclear to me though if this is an issue across countries (but that doesn't seem to be the case), or if it's an issue related to the user's network.

I have asked them to share relevant raw data with me and if/when I have it, I will update this ticket accordingly.

**Comment by hellais** [comment]
I tried searching through historical OONI data for October 2020 looking for these measurements, but could only find two measurements where WhatsApp is accessible: https://explorer.ooni.org/measurement/20201006T002727Z_AS29571_dTKzEEI4Y7ZBQBLAlZeUx9OiieTjf3otW1OG1jZqZxEgN3LfCZ
https://explorer.ooni.org/measurement/20201007T043820Z_AS36974_Tv0e5VIzD3211ak0eblk7csY8NZDJskj4ryZrmvAAhcF4uvY4u

Without a link to the measurements this issue is not actionable, hence I am closing it. If we run into this problem again we can always reopen it.

**Comment by bassosimone** [comment]
Agreed!
