### ISSUE TITLE
Measure reliability with bad connectivity

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#1600]
Moved from https://github.com/measurement-kit/measurement-kit/issues/1866

**Comment by hellais** [comment]
Sharing some notes on this topic from the last community meeting:

One of the big challenges of performing measurements in these types of scenarios is that our current testing workflow assumes that’s it’s able to reach certain services in order to bootstrap a test. The main parts of the testing workflow that require a working connection to external services are:
1. IP address lookup: if we aren’t able to do this we aren’t able to identify where a measurement is coming from. A potential workaround for this could be to use something other than geoip to get location information about the probe (see: https://github.com/ooni/probe/issues/991)
2. Provisioning of testing targets: currently we need to speak to OONI backend services in order to get a list of what should be measured. In the current model if this lookup fails it’s not possible to run a test at all. A possible workaround to this could be to a) make it possible to still run tests that don’t require provisioning of testing targets b) for those which do require targets use a cached version of the targets from some previous lookup (logic being that it’s better to test something stale than not test anything at all).
3. Test helpers: In the case of b) we need to handle also how we are going to compute the anomaly status of a particular measurement, which is currently done concurrently to the test being run by speaking to a test helper, but we could potentially move this stage to when a measurement is uploaded and “enrich” it with the needed additional fields.
4. Upload of measurements: this is relatively easy and we to some extent already support the workflow of uploading measurements at a later stage.

**Comment by bassosimone** [comment]
Closing as a duplicate of https://github.com/ooni/probe/issues/1631
