### ISSUE TITLE
Fix bug in client-side analysis of Signal & RiseupVPN measurements on OONI Probe Mobile

### ISSUE THREAD

**Issue by agrabeli** [ooni/probe#1858]
A community member from Iran just reported that their OONI Probe Mobile app is reporting that Signal and RiseupVPN are accessible, even though the OONI Explorer measurements show that they're blocked (e.g. see: https://explorer.ooni.org/measurement/20211101T184536Z_signal_IR_44244_n1_DvqRZBtixAlGVYZn).

This sounds like a client-side analysis bug.

**Comment by lorenzoPrimi** [comment]
It seems to be a typo in backend.
This is the Android code:
```
        measurement.is_failed = json.test_keys.signal_backend_status.isEmpty();
        measurement.is_anomaly = json.test_keys.signal_backend_status.equals("blocking");
```

But the json returned is
`"signal_backend_status":string"blocked"`

@FedericoCeratto can you check?

**Comment by FedericoCeratto** [comment]
@bassosimone on the backend side we are checking for a match with "blocking". Maybe the value is set incorrectly by the probe?

**Comment by bassosimone** [comment]
@FedericoCeratto @lorenzoPrimi the answer is going to be very disappointing 🤷:

1. the measurement uses `"blocked"`, so the backend is doing the right thing https://github.com/ooni/probe-cli/blob/v3.12.0-alpha.1/internal/engine/experiment/signal/signal.go#L80

2. the spec says "blocked", https://github.com/ooni/spec/blob/f9bbaa83541484e3e509ffa56dd87b0c5ce8c31a/nettests/ts-029-signal.md

3. the code to generate a summary for the measurement uses `"blocking"`, https://github.com/ooni/probe-cli/blob/v3.12.0-alpha.1/internal/engine/experiment/signal/signal.go#L192 (I don't know why it's `"blocking"` and not `"blocked"` but this seems a mistake to me)

So, I suppose this is what happened:

1. the code for the mobile probe was copied from the code in the CLI (hence it uses `"blocking"`)

2. however, the code in the CLI runs in the moment in which a measurement is generated for storing a summary for the database and, hence, it probably ends up inserting a failure into the local DB

3. my understanding is that the code in the mobile probe runs using the measurement and hence it's incorrect because it's not providing the correct result

This is what I recommend doing:

- [ ] modify the mobile probe to use `"blocked"`, which is the right value

- [ ] modify the CLI to emit `"blocked"` instead of `"blocking"` for the summary (it's inconsistent to use `"blocking"` rather than `"blocked"`) pending an assessment that this does not break the CLI and Desktop (I think it does not but certainly we cannot base actions on "I think")

- [ ] acknowledge that the code duplication between the CLI and the mobile probes is not optimal and plan refactoring to replace as much mobile code as possible with Go code being in the engine

**Comment by lorenzoPrimi** [comment]
Part 1 done here:
https://github.com/ooni/probe-android/pull/459
https://github.com/ooni/probe-ios/pull/452

**Comment by bassosimone** [comment]
There's an additional bug: the function that computes the summary uses `"blocking"` but the code generates `"blocked"`.

See: https://github.com/ooni/probe-cli/blob/v3.10.0/internal/engine/experiment/signal/signal.go#L192

**Comment by bassosimone** [comment]
I've opened https://github.com/ooni/probe/issues/1877 to describe the more general reason why this happens and to describe how we could go about fixing this issue in a more systematic way.
