### ISSUE TITLE
engine: support running signed tor binary from TOR_BINARY env var

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#1872]
We're going to ship a tor binary with probe-desktop. This requires less engineering effort than always using go-libtor (https://github.com/ooni/probe/issues/1866). We're going to sign the tor binary and verify it before running.

**Comment by hellais** [comment]
We ended up going for a different approach. Instead of looking for the tor binary inside of the same directory, we are going to pass the environment variable `TOR_BINARY` to probe-cli telling it where the binary is located. As a fallback we will search for `tor` inside of the os `PATH`.

The probe-desktop part of the integration has been done as part of: https://github.com/ooni/probe-desktop/pull/261, but we are still missing probe-cli support for parsing the TOR_BINARY env variable.

**Comment by hellais** [comment]
As mentioned in the previous comment, we aren't going this route, but have implemented the other solution. This issue can be considered done.
