### ISSUE TITLE
geolookup: use cloudflare to discover the probe's IP

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#1887]
This issue is about extending our IP lookup options inside of the `geolookup` package. We're currently using a bunch of options at random, and having more options could make our probe more reliable.

Specifically, as the title suggests, we can extend `geolookup` to add support to https://www.cloudflare.com/cdn-cgi/trace/ and/or https://www.nginx.com/cdn-cgi/trace/ as additional URLs.

It turns out that `www.cloudflare.com`, `www.nginx.com`, and any other domain hosted (fronted?) by Cloudflare have this property that you can always call the `/cdn-cgi/trace` endpoint and get back a result.

**Comment by SrijanSriv** [comment]
@bassosimone I would like to clear this issue.
I believe the geolookup has been using [`several`](https://github.com/ooni/probe-cli/blob/master/internal/engine/geolocate/iplookup.go#L37) services for getting back the probe's IP address for different cases. I think [`ipconfig`](https://github.com/ooni/probe-cli/blob/master/internal/engine/geolocate/ipconfig.go#L20) and [`ipinfo`](https://github.com/ooni/probe-cli/blob/master/internal/engine/geolocate/ipinfo.go#L25) might just be the only expendable BaseURLs since others sounds specific to their files. If I'm missing something, do chime in.
I will probably be using https://www.nginx.com/cdn-cgi/trace/ in place of these just because I've heard about it.
Thanks!

**Comment by bassosimone** [comment]
Please, do!

**Comment by bassosimone** [comment]
(Moved this issue in the Sprint backlog: @SrijanSriv has implemented it, so I need to track this issue and provide a review!)

**Comment by bassosimone** [comment]
Done!
