### ISSUE TITLE
cli: upgrade ooni/go-libtor

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#1996]
This issue is about upgrading our ooni/go-libtor dependency to use the latest version of OpenSSL, libevent, and tor. We will consider it done when we've upgrade dependencies and the cli is using the new go-libtor release.

**Comment by hellais** [comment]
This has been done over here: https://github.com/ooni/go-libtor/pull/1

**Comment by bassosimone** [comment]
So, after merging https://github.com/ooni/go-libtor/pull/1, when I build locally on macOS, I see:

```
sbs@solvecoagula ~/s/g/o/probe-cli> go get -u -v github.com/ooni/go-libtor
go: downloading golang.org/x/sys v0.0.0-20220422013727-9388b58f7150
github.com/cretz/bine/torutil/ed25519/internal/edwards25519
golang.org/x/crypto/sha3
golang.org/x/crypto/ed25519
github.com/cretz/bine/torutil/ed25519
github.com/cretz/bine/torutil
github.com/cretz/bine/process
github.com/ooni/go-libtor/libtor
# github.com/ooni/go-libtor/libtor
In file included from /Users/sbs/go/pkg/mod/github.com/ooni/go-libtor@v1.1.4/libtor/darwin_libevent_evutil_rand.go:9:
/Users/sbs/go/pkg/mod/github.com/ooni/go-libtor@v1.1.4/libtor/../darwin/libevent/compat/../evutil_rand.c:197:2: warning: 'arc4random_addrandom' is deprecated: first deprecated in macOS 10.12 - use arc4random_stir [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdlib.h:258:7: note: 'arc4random_addrandom' has been explicitly marked deprecated here
# github.com/ooni/go-libtor/libtor
In file included from /Users/sbs/go/pkg/mod/github.com/ooni/go-libtor@v1.1.4/libtor/darwin_tor_src_lib_err_backtrace.go:10:
/Users/sbs/go/pkg/mod/github.com/ooni/go-libtor@v1.1.4/libtor/../darwin/tor/src/../src/lib/err/backtrace.c:133:27: error: no member named '__rip' in 'struct __darwin_arm_thread_state64'
/Users/sbs/go/pkg/mod/github.com/ooni/go-libtor@v1.1.4/libtor/../tor_config/orconfig.macos64.h:708:44: note: expanded from macro 'PC_FROM_UCONTEXT'
```

I remember seeing this issue also previously; this happens because I'm building on arm64, while @hellais has amd64.

So, this is mostly noise, but I wanted to document it publicly for future reference.

**Comment by bassosimone** [comment]
Done!

**Comment by hellais** [comment]
> /Users/sbs/go/pkg/mod/github.com/ooni/go-libtor@v1.1.4/libtor/../darwin/libevent/compat/../evutil_rand.c:197:2: warning: 'arc4random_addrandom' is deprecated: first deprecated in macOS 10.12 - use arc4random_stir [-Wdeprecated-declarations]
> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdlib.h:258:7: note: 'arc4random_addrandom' has been explicitly marked deprecated here

I see the same warning message when doing builds on my system. AFAIK it should not cause issues on macOS builds, but only on android, where in the header the use of this function is disabled.

I suppose that if we would like to make this warning go away, we could patch the include headers to set `EVENT__HAVE_ARC4RANDOM_ADDRANDOM` to `0`.

> /Users/sbs/go/pkg/mod/github.com/ooni/go-libtor@v1.1.4/libtor/../darwin/tor/src/../src/lib/err/backtrace.c:133:27: error: no member named '__rip' in 'struct __darwin_arm_thread_state64'
> /Users/sbs/go/pkg/mod/github.com/ooni/go-libtor@v1.1.4/libtor/../tor_config/orconfig.macos64.h:708:44: note: expanded from macro 'PC_FROM_UCONTEXT'

I think that in order to get it to build properly on arm64 systems, you will have to regenerate the headers. The procedure is roughly:
1. Use https://github.com/ooni/cross-build-tor to build a `orconfig.h` from an arm64 macOS platform
2. Copy it over into a new files `tor_config/macosarm64.h`, `openssl_config/`, `libevent_config/event2/`
3. Edit `build/wrap.go` to support writing these files to the required destinations (search for `macos64` and add `macosarm64` to the list
4. Edit the top level headers in `tor_config/orconfig.h`, `openssl_config/` and `libevent_config/event2/` to have an extra case for `ARCH_MACOSARM64`
5. Edit `libtor/libtor_preamble.go` to inject the correct CFLAGS when the target platform is `darwin,arm64`

I don't have an arm64 machine available, so I can readily test this. Do we produce arm64 builds for OONI Probe at the moment? If not, I guess we should document this as work to be done once we have plans to support that.

**Comment by bassosimone** [comment]
> [...] I think that in order to get it to build properly on arm64 systems, you will have to regenerate the headers.

Yes, I am of the same advice. Because we only use ooni/go-libtor for mobile only, I think it's fine for us to wonder about this specific issue in the future rather than working on it right now. (I'll open an issue about this.)
