### ISSUE TITLE
desktop: disable riseupvpn

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#2002]
This issue is about disabling `riseupvpn` in the desktop app. The `riseupvpn` experiment has been quite flaky for quite some time. We should disable it for now and take the time to make it more resilient and useful. We will consider this issue done when `riseupvpn` is not running anymore in desktop apps _and_ we have ensured that the copy makes sense.

The `cli` related part of the work _has already been done_. What remains to be done here is to check whether we need any changes to the copy or any other adjustment in terms of UX that may be needed. Ideally this should happen during release.

**Comment by sarathms** [comment]
> What remains to be done here is to check whether we need any changes to the copy or any other adjustment in terms of UX that may be needed

About copy, we have decided that we will not be making any edits because this action will be reversed relatively soon.

As for UX, it depends a lot on how different the batch output of `probe-cli` is going to be. Since there is no released version available, theoretically it seems like this should be handled well without any changes. However, I am now going to test this by building a `probe-cli` binary from `master` to which ooni/probe-cli#679 has been merged.

**Comment by sarathms** [comment]
With RiseupVPN disabled in `probe-cli`, I was able to run the desktop app on MacOS without any changes. Below are some relevant screenshots. Except for the copy (description  on the card) and previous results, there doesn't seem to be any other reference to riseupvpn.

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/700829/152885499-bc46509e-9f56-4e5e-a508-47829f12e30c.png">

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/700829/152885639-235c9361-6fea-4e76-ac0d-2275f1b9ac20.png">

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/700829/152885659-703f95d4-1929-4f26-90aa-237641cc694f.png">

**Comment by bassosimone** [comment]
Excellent, so we can close the issue since no further change is required!
