### ISSUE TITLE
mobile: allow users to disable the VPN warning

### ISSUE THREAD

**Issue by hellais** [ooni/probe#2015]
[Here's the original issue text. See [below](https://github.com/ooni/probe/issues/2015#issuecomment-1065022710) for an updated problem description after design discussions.]

When data sharing is disabled we should not warn the user of the VPN being enabled.

We would then ideally handle the case of a measurement with a VPN at the moment of upload.

This has been reported by a user via the "Testing feedback" section of the play store.

**Comment by bassosimone** [comment]
Here's an update regarding this issue after discussions with @hellais, @agrabeli, and @aanorbel:

> When data sharing is disabled we should not warn the user of the VPN being enabled.
>
> We would then ideally handle the case of a measurement with a VPN at the moment of upload.

This strategy poses an additional issue. If a user runs tests over a VPN with data sharing being disabled, they will only discover at the moment of submitting that their time and bandwidth spent to take the measurements was wasted.

Because this is user feedback, we'd still like to address the original problem. It seems we want to allow users to tell the app to stop bothering them with the VPN setting if they insist on wanting to run measurements over VPNs.

How this would work in practice is that, when this setting is ON, the VPN-related check does not run.
