### ISSUE TITLE
mobile: run.ooni.io not working on Xiaomi devices

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#2193]
We have been informed that run.ooni.io does not work on Xiaomi for Android 11 and 12. The app does not correctly handle the run.ooni.io prefix. Attempting to open run.ooni.io using Google Chrome leads to a 502 (though, Firefox works).

![image](https://user-images.githubusercontent.com/337298/181902906-63ee99f6-75f9-4c59-a851-655eda9bf5da.png)

![image(1)](https://user-images.githubusercontent.com/337298/181902908-9e69fd3e-e431-4a49-a3af-a717a61ea8eb.png)

I am discussing and triaging this problem with users in our Slack channels.

**Comment by hellais** [comment]
It looks like the issue is in how nginx is interpreting the redirect using the `intent://` URI when we see the user-agent for Chrome on mobile (see: https://github.com/ooni/run/blob/master/index.js#L91).

The code works fine locally in development, but also when speaking to docker container directly on the host. It however stops working when speaking to nginx.

I tried setting `proxy_redirect: off` (see: http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_redirect), but that was not enough.

I also tried using the same user-agent with a smaller OONI Run link and the same issue does not occur, leading me to believe that it might have something to do with us hitting some buffer size limit in nginx (similarly to: https://github.com/ooni/sysadmin/commit/2e237ec3fb33a13aa8669b2b863c671fad43f04b)

Some more debugging is needed to understand what is going on.
