### ISSUE TITLE
Manual settings for automated testing 

### ISSUE THREAD

**Issue by sloncocs** [ooni/probe#2232]
**Feedback from the user received through contact@openobservatory.org and #ooni Slack channel**

Auto testing should use the preferences chosen for manual testing. Experimental tests that runs during auto test seems to cause all interweb connections to receive heavy interference, the methods experimental tests use are well known for causing ones all interweb connections to get interfered by some well known entity when in use. Some website categories and communication softwares can also cause all interweb connections to get interfered during the test.

Auto tests currently seems to run all the tests without options to disable unwanted tests.

**Additional context**

Apart from interferences, there is a concern that some tests use much more traffic than others which might be crucial for the users in some countries, e.g., Uzbekistan. Another issue is that the user cannot exclude anything that could be perceived as riskier to test. It’s also from the Uzbekistan example that I mentioned in the issue, local providers have the practice to cut the connection for a few weeks and say that there are ‘some tech works to be done’ if people, esp activists, try to reach some ‘forbidden’ content. Within such a context, it would be almost impossible to persuade anyone to run automated tests without manual settings.

**Comment by agrabeli** [comment]
My understanding is that this would involve having the ability to manually determine which test(s) are run automatically. Is that correct? 

In that case, it's a question of perhaps **adding settings to the Automated Testing section** of OONI Probe that enable users to determine whether they want to have all tests (excluding performance tests) run automatically, or if they would like to enable certain tests (or class of tests) for automated testing. 

This may require work on probe-cli (cc' @bassosimone), determining the UI for the new settings (cc' @hellais), and implementing the new UI in OONI Probe (cc' @aanorbel @majakomel ).

**Comment by agrabeli** [comment]
Apart from manually determining which tests are run automatically, we may want to have a separate ticket on manually determining which websites (or lists of websites) are automatically tested.

**Comment by agrabeli** [comment]
Thanks @sloncocs for bringing this to our attention! <3

Following team discussion, it turns out that the following **already apply in terms of settings for automated runs**:

- **Website category settings (both automated & manual runs)** -> OONI Probe Desktop and OONI Probe Mobile
- **Test Options settings (both automated & manual runs)** -> Only OONI Probe Mobile (Android & iOS)

The reason why the Test Options settings don't apply to OONI Probe Desktop is because it doesn't include settings (beyond website testing) for the tests yet. I have therefore opened this ticket: https://github.com/ooni/probe/issues/2267. Once this has been implemented, we can ensure that the configuration of Test Options also applies to automated testing on OONI Probe Desktop: https://github.com/ooni/probe/issues/2265

Moreover, we'll be adding a new Experimental setting (under Test Options) that will enable users to determine whether they would like to have experimental tests included in manual and automated runs, or not. See ticket: https://github.com/ooni/probe/issues/2266

**Comment by hellais** [comment]
This has been implemented for mobile here: https://github.com/ooni/probe-android/pull/543
