### ISSUE TITLE
miniooni: add --disable-ipv6 command line flag

### ISSUE THREAD

**Issue by arky** [ooni/probe#2324]
**Describe the bug**
My ISP doesn't allow IPV6.  I do not have any IPV6 tunnels setup. Currently ooni tests for IPV6 connections by default. This behavior results in too many requests failures. 

I propose two solutions: Provide a  '--disable-ipv6' command line option to disable IPV6 test all together. 

Internally, the tool should check if IPV6 is available and disable tests if the network is not available or fails consistently with network unreachable errors.
```
[      3.046253] <info> [#5] GET https://fark.com using [2604:a880:800:c1::20a:2001]:443... network_unreachable
[      3.046382] <info> [#6] GET https://fark.com using [2604:a880:800:c1::16c:6001]:443... network_unreachable

```
***Additional context**
Testing done with master branch miniooni custom build and using web_connectivity@v0.5

**Comment by bassosimone** [comment]
Since when you tested, we've improved Web Connectivity v0.5 to detect and ignore IPv6 issues. I could obviously add a `--disable-ipv6` flag to miniooni, but the reality is that most measurements run using OONI Probe Android or OONI Probe Desktop, where adding this flag would be much less practical because we want to provide an easier user experience. As such, I think I'm going to be happy we are addressing the issue with post processing and won't implement the flag. Thank you for opening this issue and thank you for testing Web Connectivity v0.5! 🙏
