### ISSUE TITLE
OONI test detection bug

### ISSUE THREAD

**Issue by SlashyID** [ooni/probe#2345]
[An OONI Probe test](https://explorer.ooni.org/measurement/20221023T200324Z_webconnectivity_ID_38511_n1_IaidRWoP1fNwgYju?input=http://pornhub.com) doesn't show as Confirmed Blocked even the DNS fingerprint is already [listed here](https://github.com/ooni/blocking-fingerprints/blob/main/fingerprints_dns.csv) 

The same bug can be seen in other measurement such as [this](https://explorer.ooni.org/measurement/20221023T200324Z_webconnectivity_ID_38511_n1_IaidRWoP1fNwgYju?input=http://vimeo.com) and [this](https://explorer.ooni.org/measurement/20221023T200324Z_webconnectivity_ID_38511_n1_IaidRWoP1fNwgYju?input=http://xnxx.com)

Please fix this thank you

**Comment by agrabeli** [comment]
I think a reason why it may not be displayed as `confirmed` yet is because the fingerprint has been added to https://github.com/ooni/blocking-fingerprints/, which is the repo that I think `ooni/data` (our new pipeline for more advanced analysis) uses, as opposed to the `ooni/pipeline` repo which is currently used for displaying measurements on OONI Explorer.

@FedericoCeratto @hellais can you please confirm? And if that is the case, can we add those fingerprints to the `ooni/pipeline` repo as well?

**Comment by bassosimone** [comment]
@agrabeli that is correct

**Comment by SlashyID** [comment]
Can you fix it please? **[It still showing anomaly instead of Confirmed Blocked here](https://explorer.ooni.org/measurement/20221121T202618Z_webconnectivity_ID_38511_n1_C1igAV4lZ6lDw8YH?input=http://xhamster.com)**
