### ISSUE TITLE
probe-ios: background task notifications are sometimes undefined and lead to app crash

### ISSUE THREAD

**Issue by hellais** [ooni/probe#2349]
It's not very reproducible, but sometimes when I pick up my phone in the morning, the OONI Probe notifications (which I assume are for the daily autorun) show "undefined" in the text field and when I tap on the notification it opens the app, but it crashes soon thereafter.

**Comment by aanorbel** [comment]
This issue is particularly difficult to reproduce since there are no direct steps to follow. I will look into Automated runs and related notifications to try and figure it out.

**Comment by hellais** [comment]
@bassosimone mentioned that he has the same behaviour. @aanorbel I think you said that you don't see it happen on your iOS device.

Could you share a screenshot of the notifications you see on your device?

This is how the notifications look like on iOS for me:

![D313DB67-7FCE-4A80-973C-30AEC218D413](https://user-images.githubusercontent.com/424620/236470319-ce5c467f-2fbb-4283-9163-37bbe93dec8a.png)

![9DBBBF81-5161-4AD3-9AE6-6C54697C3E04_1_105_c](https://user-images.githubusercontent.com/424620/236470308-ea84d9ce-9049-4852-9afb-2a6a58b2618b.jpeg)

**Comment by aanorbel** [comment]
I can confirm that the problem occurs with automated runs every single time and not sometimes.
`test_group_name` is never set for automated runs since `storeDB` is always false
https://github.com/ooni/probe-ios/blob/b89b297b0e08fd403aa46f4e61561743d67f4d36/ooniprobe/Test/Suite/AbstractSuite.m#L113-L122.

So when the app tries to use the value, it is empty and hence the `null` is shown 

https://github.com/ooni/probe-ios/blob/b89b297b0e08fd403aa46f4e61561743d67f4d36/ooniprobe/Test/Suite/AbstractSuite.m#L97
