### ISSUE TITLE
webconnectivity: add HTTP/3 support to the testhelper

### ISSUE THREAD

**Issue by kelmenhorst** [ooni/probe#2355]
The webconnectivity testhelper (`internal/cmd/oohelperd`) should support HTTP/3 host discovery and HTTP/3 measurements. For the prototype, we inspect the `Alt-Svc` HTTPS header which by convention indicates the HTTP/3 support of a given host via the HTTP response.  If HTTP/3 support has been discovered, the testhelper should measure the HTTP/3 endpoint by performing a QUIC handshake and fetching the resource via HTTP/3, and transmit this information to the probe.

**Comment by kelmenhorst** [comment]
In the future, we also wanna think about
- [ ] whether we can use e.g. pings to do active QUIC host discovery that runs periodically on the testhelper
- [ ] whether we should use DNS HTTPS records for discovering HTTP/3 hosts in the lookup phase

**Comment by bassosimone** [comment]
> In the future, we also wanna think about
> 
>     * [ ]  whether we can use e.g. pings to do active QUIC host discovery that runs periodically on the testhelper
> 
>     * [ ]  whether we should use DNS HTTPS records for discovering HTTP/3 hosts in the lookup phase

@kelmenhorst do you think we should create issues about these two points? This issue is now technically complete and I will make sure we remember to close it such that you collect all the rings from completing it.

![sonic-sega](https://user-images.githubusercontent.com/337298/206713039-5b95e612-a407-4646-8f1b-20be6d52c1d2.gif)

**Comment by bassosimone** [comment]
Thanks!
