### ISSUE TITLE
Store DNS additional answer in OONI data

### ISSUE THREAD

**Issue by Te-k** [ooni/probe#2373]
Hi,

One ISP in France is providing some interesting additional data when censoring a website in DNS additional data : 
```
dig libgen.rs

; <<>> DiG 9.18.8-1-Debian <<>> libgen.rs
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 48155
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 2

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; COOKIE: 86fd76bbf9cd28da0100000063832b9cd9165dee9adce850 (good)
;; QUESTION SECTION:
;libgen.rs.			IN	A

;; ANSWER SECTION:
libgen.rs.		5	IN	A	127.0.0.1

;; ADDITIONAL SECTION:
justice-autre.		1	IN	SOA	ns1.orange.fr. postmaster.wanadoo.com. 2022112521 216000 3600 3600000 172800
```

The additional section is a part of the DNS answer message that contains a DNS entry having the same format as the answer section. 
Have you seen that in other countries? If yes, I think it would be a useful addition to the data gathered by the OONI probe and could be stored in the DNS test results.

**Comment by YadavGulshan** [comment]
Hi!

I found the similar response for `carrefour.fr`.

```
; <<>> DiG 9.18.12-0ubuntu0.22.04.2-Ubuntu <<>> carrefour.fr
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 4993
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 5, ADDITIONAL: 6

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;carrefour.fr.			IN	A

;; ANSWER SECTION:
carrefour.fr.		3600	IN	A	104.18.7.94
carrefour.fr.		3600	IN	A	104.18.6.94

;; AUTHORITY SECTION:
carrefour.fr.		3579	IN	NS	antor.carrefour.com.
carrefour.fr.		3579	IN	NS	pendragon.carrefour.com.
carrefour.fr.		3579	IN	NS	keu.carrefour.com.
carrefour.fr.		3579	IN	NS	ns1.eu.rrpproxy.net.
carrefour.fr.		3579	IN	NS	ns2.eu.rrpproxy.net.

;; ADDITIONAL SECTION:
keu.carrefour.com.	113467	IN	A	213.137.173.17
antor.carrefour.com.	113467	IN	A	217.77.225.150
pendragon.carrefour.com. 113467	IN	A	217.77.230.17
keu.carrefour.com.	113467	IN	AAAA	2a00:2000:4701:d::1
pendragon.carrefour.com. 113467	IN	AAAA	2001:67c:280c:d::1

;; Query time: 252 msec
;; SERVER: 127.0.0.53#53(127.0.0.53) (UDP)
;; WHEN: Mon Jul 24 15:08:04 IST 2023
;; MSG SIZE  rcvd: 303
```

I'm looking to work on this issue. It would be great if you can refer me what part I should look on.

**Comment by bassosimone** [comment]
@Te-k @YadavGulshan The next version of Web Connectivity that we're going to probably ship in the March release performs DNS-over-UDP and collects DNS responses. See, for example, [this measurement](https://explorer.ooni.org/m/20240208142847.612563_IT_webconnectivity_920bacc0600576e1). Check the `test_keys.queries[0]` entry. The raw response is the base64 of the bytes we received, therefore it includes the sections you're interested in.

If you have some spare cycles to check whether this is actually the case, that would be awesome! To this end, your should either compile `miniooni` for yourself (see [instructions](https://github.com/ooni/probe-cli/?tab=readme-ov-file#common-build-targets)) from the `master` branch or [use a nightly build](https://github.com/ooni/probe-cli/releases/tag/rolling).

The command to run is:

```bash
./miniooni -i https://libgen.rs/ web_connectivity@v0.5
```

(Add `-y` to the command line if it's the first time that you use `miniooni`.)

Towards the end of the output, the command will print the Explorer URL of the measurement.

I am tentatively going to close the issue because AFAICT it should be possible to observe the additional sections. Please, reopen the issue if Web Connectivity v0.5 does not collect all the data you need.

Thank you!

**Comment by Te-k** [comment]
That's great, thanks!
