### ISSUE TITLE
probe-cli: does not build with go 1.20

### ISSUE THREAD

**Issue by PolynomialDivision** [ooni/probe#2478]
It gives following warnings. Please update quic-go version.
```
/builder/dl/go-mod-cache/github.com/lucas-clemente/quic-go@v0.31.1/internal/qtls/go120.go:5:13: cannot use "The version of quic-go you're using can't be built on Go 1.20 yet. For more details, please see https://github.com/lucas-clemente/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.20 yet. F...) as int value in variable declaration
```
Please update

**Comment by jefferyto** [comment]
@bassosimone it appears Psiphon-Labs/quic-go has been updated to support 1.20 but Psiphon-Labs/psiphon-tunnel-core hasn't been updated yet - perhaps you can ask the Psiphon devs?

**Comment by bassosimone** [comment]
Thank you @PolynomialDivision and @jefferyto!

**Comment by bassosimone** [comment]
@jefferyto we could update Psiphon but there is one extra issue. We vendor modified `crypto` (https://github.com/ooni/oocrypto) and `net/http` (https://github.com/ooni/oohttp) to improve resilience and allow using nonstandard TLS libraries respectively. However, the standard library is not designed to be modular, so there _may_ be implicit coupling between our vendored libraries and the standard library we're linking against. Because of this reason, the safest choice in terms of compiling ooniprobe is using the same standard library and Go compiler from which we forked our vendored libraries. Currently, this version of Go is 1.19.6. This is why, even if we update Psiphon, I would not recommend compiling ooniprobe using Go 1.20.x and would recommend sticking to Go 1.19.6, if possible. (That said, we're going to need to update to Go 1.20 ~soon anyway because we're approaching the EOF for the 1.19.x series.)

**Comment by bassosimone** [comment]
We're making progress on this issue. There's an alpha release out with go1.20 support: https://github.com/ooni/probe-cli/releases/tag/v3.18.0-alpha. Thanks again for prodding me to address this issue!

**Comment by stefanb** [comment]
FYI, Go 1.21 will be released soon (see [rc2 announcement](https://groups.google.com/g/golang-announce/c/REcCdQj1taA)), making the Go 1.19 not maintained anymore.

**Comment by bassosimone** [comment]
@stefanb thanks for he heads up!

**Comment by bassosimone** [comment]
I am going to close this issue, given that https://github.com/ooni/probe-cli/releases/tag/v3.18.0 supports go1.20 🥳
