### ISSUE TITLE
Include scanning to the list of available ooni-probe tests

### ISSUE THREAD

**Issue by anadahz** [ooni/probe#489]
Currently ooni-probe lists tests from `blocking`, `manipulation`, and `third_party` test categories.
Shall we add the `scanning` test category as well?

**Comment by hellais** [comment]
There is actually only one test inside of the scanning directory (`http_url_list`). To be honest I am not fully convinced that we should be including this test as part of the distribution due to how hard it is to configure it properly.

I would suggest we instead move it into the experimental source tree.

**Comment by hellais** [comment]
Issue moved to [ooni/probe-legacy #19](https://github.com/ooni/probe-legacy/issues/19) via [**ZenHub**](https://www.zenhub.com/)
