### ISSUE TITLE
Add delay between testing of input lists

### ISSUE THREAD

**Issue by hellais** [ooni/probe#513]
@willscott pointed out while reviewing #457 that it would be nice to have some logic that adds a delay between requests to recuperate from network failure.

I think this would be a very useful feature to have, perhaps implementing something like exponential backoff based on the failure rate of requests.

**Comment by willscott** [comment]
This is part of a larger enhancement we should be thinking about in test scheduling. In particular, this should be implemented as a byproduct of backing-off / retrying tests if the network starts failing at an unexpected rate. We should also shuffle the test lists each run to mitigate correlated failures.  (visiting google.com causes my connection to reset and whatever's scheduled right after that domain will never load because of its position in the list)

**Comment by bassosimone** [comment]
I have already implemented exponential backoff in the new ooni/probe-engine. When all tests will be rewritten in Go, they will get this functionality for free. I am closing this issue now.
