### ISSUE TITLE
Improve UI related to keeping/unkeeping measurements

### ISSUE THREAD

**Issue by anadahz** [ooni/probe#591]
When a user use the keep action button a `keeping` tag is being added with not way to remove it.

It makes sense for a "not-keep" or undo action button that will revert of saving the specific report forever but not delete it until the default "keep" period.

**Comment by hellais** [comment]
This was actually a design choice as I figured that the user will either want to keep a measurement or delete it. If they have changed their mind with regard to keeping it, then why would they want to not just delete it directly?

I also suspect it makes the behaviour somewhat confusing if they hit the unkeep button after the 7 day period has passed, since that is basically equivalent to hitting the delete button.

As such I am leaning towards not having support for unkeeping a measurement.

**Comment by anadahz** [comment]
I see your point perhaps we should a help icon somewhere to explain the intended behavior of the GUI.

**Comment by hellais** [comment]
Issue moved to [ooni/probe-legacy #53](https://github.com/ooni/probe-legacy/issues/53) via [**ZenHub**](https://www.zenhub.com/)
