### ISSUE TITLE
Make scapy a soft dependency of ooniprobe

### ISSUE THREAD

**Issue by hellais** [ooni/probe#654]
It seems like scapy (and it's depedencies pypcap and libdnet) are quite problematic to get working on all systems.

Since we don't really need it for the majority of the ooniprobe tests it would be good if we could make it a soft dependency and make the software be installable and runnable (but with a limited set of features) when scapy is not installed.

**Comment by gpotter2** [comment]
Hi !
If you have any issues while installing scapy, feel free to report it to https://github.com/secdev/scapy

We have improved a lot scapy with its latest releases (2.4.0+), so that it supports Windows and OSX without any dnet, and made it work with many different depedencies (pypcap, libpcap, pcapy).

**Comment by hellais** [comment]
Issue moved to [ooni/probe-legacy #33](https://github.com/ooni/probe-legacy/issues/33) via [**ZenHub**](https://www.zenhub.com/)
