### ISSUE TITLE
No blocked websites in China and issue with Android app

### ISSUE THREAD

**Issue by theincogtion** [ooni/probe#794]
The ooni probe explorer shows "no blocked websites" in china (is this a joke?) and the android app does not show the results of the tests. It loads indefinetly

![image](https://user-images.githubusercontent.com/10852327/43034799-95f9d374-8ce3-11e8-8b87-81b96f1a1e12.png)

**Comment by hellais** [comment]
Hi @theincogtion, thanks for reaching out!
 
> The ooni probe explorer shows "no blocked websites" in china

In OONI Explorer we currently only "confirm" the blocking of websites in cases in which:

a. We see a blockpage (example blockpage in Italy: https://explorer.ooni.io/measurement/20170811T041513Z_AS30722_UqEo2LfOeajXl4AUeITt6Ba31wTZISdL0qJMORjM8Lb0eyqZIA?input=http:%2F%2Fextratorrent.com)
b. We have classified that page as a blockpage and our data analysis pipeline can mark them as confirmed blocked

Since China doesn't serve blockpages, but instead either sends a spoofed DNS response with some IPs that are not always associated to HTTP servers or terminates connections by injecting TCP RST packets, we aren't currently able to mark those as confirmed.

We are working on improving our heuristics to take into account for other other blocking events, but for confirmed cases we prefer to air on the safe side and will not confirm a case of blocking unless we have a very high degree of certainty.

> and the android app does not show the results of the tests. It loads indefinetly

Can you clarify what this means?

This seems like a bug in the Android app, which you should report here: https://github.com/ooni/probe-android/issues/new

**Comment by hellais** [comment]
No response. Closing.
