### ISSUE TITLE
Evaluate what are the best translations for commonly used OONI lingo

### ISSUE THREAD

**Issue by hellais** [ooni/probe#809]
There are various words we use in the OONI Probe app that are hard to translate in the various languages.

We should come up with some best practices for translating these in the various languages for the upcoming revamped app.

A partial list of these terms are:

* Middleboxes
* Instant Messagging
* NDT Speed Test
* Performance

As we identify more, let's add them to this ticket

**Comment by elioqoshi** [comment]
Are you sure there is anything we can do about this? I mean every language handles it differently. e.g some languages like Greek translate "Link" even while some others like German don't translate it. I think this should be process curated by the local l10n communities rather coming from the core OONI team.

(I also realize this issue is 1 year old but anyway)

**Comment by hellais** [comment]
@agrabeli has done some great work on implementing this here: https://github.com/ooni/ooni.org/pull/298
