### ISSUE TITLE
The process of data submission is unclear

### ISSUE THREAD

**Issue by mrphs** [ooni/probe#825]
At no point in the app there's a notification or prompt about the data being pushed to the pool and whether it has successfully be executed.

I think the data submission process needs some error handling with some UI.

Immediately after a test is successfully ran, is the best **first** place to ask users if they want to consent to their data being published. And if they did, it would be nice to have a progress bar to monitor it.

Also, it's unclear whether it's being published over .onion, TLS or plain HTTP. Given the fact that now you can wrap Tor in iOS apps, I was presuming ooni has Tor built in, and is using onion by default to submit the data. I don't find anywhere in the app mentioning such a thing so I assume I was wrong but I hope it's on the roadmap. It could be exemplary for other iOS apps.

**Comment by elioqoshi** [comment]
Users are made aware of this in the onboarding and Publishing results can be disabled in Settings as far as I understand. 

I'm still unsure how the upload process of finished tests works @bassosimone. Would we be able to show a progress bar in a test result if a test is currently being uploaded?

Also, what happens if a user (who has Publish results enabled in Settings) runs a web connectivity test successfully and right after closes the app (or even uninstalls it). Would these results be uploaded or not? Would they be partial?

**Comment by bassosimone** [comment]
> Users are made aware of this in the onboarding and Publishing results can be disabled in Settings as far as I understand.

Understanding is correct.

> I'm still unsure how the upload process of finished tests works @bassosimone. Would we be able to show a progress bar in a test result if a test is currently being uploaded?

My understanding is that there is a already a progress bar. This makes complex showing a progress bar related to uploading measurement results because that happens as part of running a test.

> Also, what happens if a user (who has Publish results enabled in Settings) runs a web connectivity test successfully and right after closes the app (or even uninstalls it). Would these results be uploaded or not? Would they be partial?

The results are uploaded on the go, as we test URIs. When the test is complete, it _also_ means that all results have been uploaded.

**Comment by hellais** [comment]
@agrabeli do you think there is some actionable output from this?

**Comment by hellais** [comment]
I would say we already take several steps to ensure that it's clear to the user the data is automatically published by:

1. We explain that data is by default going to be published during the onboarding
2. We test that they understood this by prompting them with a quiz
3. We have this as documentation available on our website
4. There is a setting that allows users to disable the automatic upload of data

If you have some concrete suggestions on how we can further improve this, we are happy to discuss that in another issue.

Closing.
