### ISSUE TITLE
Group the middlebox tests with the performance test group

### ISSUE THREAD

**Issue by lorenzoPrimi** [ooni/probe#835]
The two middlebox tests will be inserted in the Performance tests.
- Header in test details will stay the same as performance, only two more rows will be added
- The row in test results will not change
- The copy in the Test Overview will be changed based on the Performance test

**Comment by elioqoshi** [comment]
That's a huge change which needs to be well considered. What's the motivation? How would it be nested within Websites card? What would the userflow roughly look like?

**Comment by lorenzoPrimi** [comment]
It's @hellais idea, he will explain it more

**Comment by elioqoshi** [comment]
I think their semantics distinguish them more than they bring them together though. 

If this would be something we would do, I guess the hierarchy would be similar to this:

Websites
- Web Connectivity
- - URLs
- HTTP Header Field Manipulation
- HTTP Invalid Request Line

**Comment by bassosimone** [comment]
I'm fine with doing this kind of grouping! 👍

**Comment by hellais** [comment]
I somehow recalled this being discussed also in some other ticket (I only was able to find https://github.com/ooni/probe/issues/929 as related) and that we came to the conclusion it should instead be grouped with the Performance tests.

Since I can't find that I will explain why I think that should be the correct grouping.

The Middlebox tests are somehow more closely related to the performance test since:

*  They are telling you stuff related to "properties of your network"
*  Middlebox technologies are commonly used to implement caching which has an impact on performaance
* In OONI Explorer we display the results related to middlebox tests in the networks section next to the performance test results (see screenshot below)

<img width="1301" alt="Screenshot 2020-02-21 at 14 38 34" src="https://user-images.githubusercontent.com/424620/75038972-e7a01d80-54b7-11ea-9e76-17e55327c00e.png">

Because of the above reasons I suggest we rather put them inside of the Performance tests section.

The other benefit of doing this is that we don't have to completely rethink the UI, because showing the middlebox results next to the websites tests would mean having to think of how to show the many URL input rows together with the HIRL and HHFM test rows.

@bassosimone what do you think about this reasoning?

**Comment by bassosimone** [comment]
@hellais sure, go ahead!

**Comment by lorenzoPrimi** [comment]
Issues to be handled for the implementation of this card:
- Test Overview copy and layout
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-20 at 14 16 36](https://user-images.githubusercontent.com/1616097/79750675-a2f6fe00-8311-11ea-8ed0-811eb8ff2619.png)
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-20 at 14 16 38](https://user-images.githubusercontent.com/1616097/79750679-a4c0c180-8311-11ea-9d02-3c70e68242c6.png)

**Comment by lorenzoPrimi** [comment]
-Test result rows
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-20 at 14 17 24](https://user-images.githubusercontent.com/1616097/79750717-b1ddb080-8311-11ea-8525-024086d5526a.png)

**Comment by lorenzoPrimi** [comment]
- Test result header
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-20 at 14 17 47](https://user-images.githubusercontent.com/1616097/79750755-c457ea00-8311-11ea-8d42-e0a9333c9374.png)
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-20 at 14 17 51](https://user-images.githubusercontent.com/1616097/79750758-c7eb7100-8311-11ea-8863-30fca83460a5.png)

**Comment by hellais** [comment]
I think that the only thing that needs to be changed is the copy inside of the details of the performance card.

The test result header stays the same and no metadata pertaining to the middlebox test results should be exposed in the result list view.

**Comment by lorenzoPrimi** [comment]
NOTE TO SELF:
There is some code that can be safely removed, for now it's gonna be marked with 
`    //TODO-MB safely remove`
and some other code that cannot be touched as user have the middle boxes tests in their database and they requires the icon, the color and the MiddleBoxes Test Class. These will be marked as
`    //TODO-MB remove in the future`

**Comment by lorenzoPrimi** [comment]
Another solution would be to change every `Result.test_group_name` in the database from `middle_boxes` to `performance`

**Comment by lorenzoPrimi** [comment]
We probably don't  want to release this until we have a copy and translations

**Comment by agrabeli** [comment]
As part of merging the performance & middlebox tests into 1 card, we can use the following copy for the card:

> By running the tests in this card, you will:
> 
> * Measure the speed and performance of your network ([NDT](https://ooni.org/nettest/ndt/) test)
> 
> * Measure video streaming performance ([DASH](https://ooni.org/nettest/dash/) test)
> 
> * Check for the presence of [middlebox technologies](https://ooni.org/support/glossary/#middlebox) on your network ([HTTP Invalid Request Line](https://ooni.org/nettest/http-invalid-request-line/) and [HTTP Header Field Manipulation](https://ooni.org/nettest/http-header-field-manipulation/) tests)
> 
> These tests consume data depending on your network speed.
> 
> Your test results will be published on [OONI Explorer](https://explorer.ooni.org/) and [OONI API](https://api.ooni.io/).
> 
> Disclaimer: The [NDT](https://ooni.org/nettest/ndt/) and [DASH](https://ooni.org/nettest/dash/) tests are conducted against third-party servers provided by [Measurement Lab (M-Lab)](https://www.measurementlab.net/). If you run these tests, M-Lab will collect and publish your IP address (for research purposes), irrespective of your OONI Probe settings. Learn more about M-Lab’s data governance through its [privacy statement](https://www.measurementlab.net/privacy/).
