### ISSUE TITLE
Allow users to easily copy the report ID

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#856]
Requested by community member at IFF. This should be an option in the top right menu allowing users to copy the report ID, according to @elioqoshi (IIRC).

**Comment by lorenzoPrimi** [comment]
@bassosimone so you propose another item in the menu* "Copy report ID" ?
*The menu with view raw data and view log
If yes this can be address already in 2.2.0

**Comment by bassosimone** [comment]
Yes, that was my suggestion, @lorenzoPrimi !

**Comment by hellais** [comment]
I would suggest that we expose this as "Copy Explorer link" so that when the measurement is processed they can just click on the link and access the measurement.

Copying only the report_id leads to the reference not being unique for tests which have many URLs.

I guess that since we now have in the app support for detecting if the measurement is uploaded we can even handle the case of the measurement not yet processed in a "special" way (for example by displaying a note saying that it may take up to 24h for the link to become "active").

For power users that actually just case about the report_id this should work well for them as well, since the explorer URL includes the report_id too.

**Comment by lorenzoPrimi** [comment]
Ho do we get explorer url?
In this link is not present https://api.ooni.io/api/v1/measurements?report_id=20190113T202156Z_AS327931_CgoC3KbgM6zKajvIIt1AxxybJ1HbjwwWJjsJnlxy9rpcGY54VH

**Comment by hellais** [comment]
The explorer URL is:
```
https://explorer.ooni.io/measurement/$REPORT_ID?input=$INPUT
```

If the measurement does not have an inpute, then you will omit the `?input=$INPUT` section.

**Comment by lorenzoPrimi** [comment]
@hellais can I call the `https://api.ooni.io/api/v1/measurements?` api and return an error in case there is no report or open the explorer url in case there is?
The first function is already done and tested

**Comment by hellais** [comment]
I think it's useful to support copying and sharing the explorer URL even if it's not yet "live".

Maybe what we can do is detect if the measurement is uploaded and if that is the case display a modal when the user copies it saying it's not yet uploaded and will be available within 24h.

**Comment by lorenzoPrimi** [comment]
When entering the measurement page the app will check if the measurement has been published (if the file exists on disk)
If the measurement is not available on explorer the "Copied to clipboard" message will have also a subtitle "will be available within 24h"
