### ISSUE TITLE
Misleading error msg when security cert disabled (or missing?)

### ISSUE THREAD

**Issue by IronJunkie** [ooni/probe#858]
Ooni app could not run website blocking test as it couldn't download URL list. I eventually found this was due to the "Digital Securiy Trust" certificate being disabled on this device, but the error msg did not suggest a security certificate issue, though obvious in hindsight.

## Expected Behavior
error message displayed related to security certificate if app cannot reach server to download url list to run test due to security certificate issue

## Actual Behavior
Error message "Unable to download url list. Please try again" is displayed suggesting some other issue ie internet connection issue. (The website blocking test does not run as it cannot download url list.)

## Steps to Reproduce the Problem

  1. Disable "Digital Securiy Trust" certificate in Android settings
  2. Run Website blocking test
  3. Test fails to run & internet connection error msg displayed.
  
Note: all other tests seem to run as expected so I didn't consider security certificates at first, assumed issue was likely with ooni server

## Specifications

  - Version: ooni prob 2.0.3 measurement kit 0.9.3
  - Platform: Android 9.0, April 2019 security patch, Essential PH-1

**Comment by hellais** [comment]
@bassosimone @lorenzoPrimi do you have ideas as to why this may be happening?

**Comment by bassosimone** [comment]
@hellais yes: we use Android code to fetch the test lists. This is using the certificates available on Android. Unfortunately a certificate, the one we use, is disabled.

Also, I agre with @IronJunkie that the error message is bad. I believe we should always have a real error message along with a simpler one, because it allows tech savvy people to debug quickly.

I believe more in the long term we should always be using our CA for all our operations.

Thanks for pointing me at to this issue!

**Comment by hellais** [comment]
I moving this into OONI Measurements as I think it's mostly relevant to probe-engine at this point.

**Comment by bassosimone** [comment]
Right. This really calls for forcing our own CA. Because the CA is relatively small, I am leaning towards an alternative approach where, rather than downloading it, we bundle is a text and install it.

This implies that we should do scheduled releases of probe-engine, say, every two months, such that we are reasonable sure that the CA that we're bundling is current enough.

@hellais what do you think?

**Comment by bassosimone** [comment]
We're now forcing our own CA. This does not solve the problem, though, because the code that the mobile app is using for fetching URLs still depends on the system certificate store. To make this possible we also need to further refactor and change the way in which OONI for mobile runs.

**Comment by bassosimone** [comment]
> This does not solve the problem, though, because the code that the mobile app is using for fetching URLs still depends on the system certificate store. [...]

However, as far as _measuring_ is concerned, the problem has now been fixed. I will keep this issue open because, strictly speaking, we have not eliminated _all_ the dependencies from system certificates, but we eliminated the ones that matter the most.

**Comment by bassosimone** [comment]
On second thought, because the original issue has been _morally_ addressed, I believe it is better to close this issue in Sprint 21 _as well as_ to create a follow-up issue regarding using more Go code in the mobile apps. By always using Go code in the mobile apps for accessing OONI services we will be addressing the remaining part of this issue and also have additional benefits such as automatic fallback to different probe services, etc. Part of this work has already been specced at https://github.com/ooni/probe-engine/issues/893.

**Comment by bassosimone** [comment]
The effort is `1` because there's need to take some time and create clearly specced follow-up issues.

**Comment by bassosimone** [comment]
Priority is low because we just need to create follow-up issues at this point.

**Comment by bassosimone** [comment]
Follow-up issue here: https://github.com/ooni/probe-engine/issues/899. Closing as explained at https://github.com/ooni/probe/issues/858#issuecomment-683617908.
