### ISSUE TITLE
View data button does not work for gmail.com

### ISSUE THREAD

**Issue by hellais** [ooni/probe#865]
## Expected Behavior
When I tap the Data button in the option menu I should be able to inspect the raw measurement data.

## Actual Behavior

When I tap on the button nothing happens if I have tested the site `https://gmail.com`

## Steps to Reproduce the Problem

  1. Choose a custom site and test `https://gmail.com`
  2. Run the experiment
  3. Go the measurement detail page and notice how it's not possible to view the data

## Specifications

  - Version: 2.1.0-beta.4
  - Platform: Android

**Comment by lorenzoPrimi** [comment]
@hellais is this something worth doing in react?

**Comment by hellais** [comment]
@lorenzoPrimi yeah this could be one of such things.

**Comment by hellais** [comment]
Since we didn't have a issue for the react-native feature I made one here: https://github.com/ooni/probe/issues/868

**Comment by hellais** [comment]
> @hellais is this something worth doing in react?

I mean I don't actually think react is going to solve this problem here. The issue, from what I can tell, is that the JSON parser we are using cannot handle big files too well.

@lorenzoPrimi maybe what we want to do is benchmark the performance of the JSON parser we are using in the app and understanding where the bottleneck is.

It is unclear to me if the issue occurs when you parse the JSON or just when you attempt to render it. If the issue is in rendering then we can consider something on that front once we understand which aspect of rendering the file is causing problems.

In any case some more Root Cause Analysis needs to be done on this problem to better quality it and determine what is the best solution based on that.

**Comment by bassosimone** [comment]
@hellais just for me to understand well the issue. Is it correct to state that the issue is that we cannot see the pretty printed measurement JSON which only consists of text? If that's the case, I believe we can have a MK (and, in the future, ooni/probe-engine) API that pretty prints the JSON for the app.

This seems to me a way to solve the problem I described, which admittedly may not be the problem that we actually have, in much less time. (It can land in MK v0.10.5 and OONI mobile v2.2.2.)

So, do I understand the problem correctly? Is my proposed solution worth doing?

In defence of my proposed solution, it's a no brainer consisting of very few lines of code that can be implemented directly in mkall-ios and android-libs without touching MK core.

**Comment by hellais** [comment]
I don't understand the issue very well myself, that is why I am asking @lorenzoPrimi if he can do some more testing to understand what is the root cause of the slowdown.

**Comment by lorenzoPrimi** [comment]
It's very simple, no way you can load a 1.3MB text into a textview, expecially with the old phones.
Other jsons are a few kb, this one is just too big to be rendered (it eventually will be rendered but takes too much time)

**Comment by lorenzoPrimi** [comment]
@bassosimone don't focus on "pretty printed", it does the same thing with not pretty printed, just tested it

**Comment by bassosimone** [comment]
@lorenzoPrimi now I understand the issue at hand, thank you. I believe we should fix this problem by loading the JSON in a data structure and, in such structure, modify the HTTP body manually so to keep only the first 1,024 KiB of the body. This would fix loading into a textview, right?

**Comment by lorenzoPrimi** [comment]
I have no idea what you are suggesting here!
What causes the problem is actually load the file into memory and then display it. 
I'm wondering which one of these two tasks is the most memory consuming.

**Comment by bassosimone** [comment]
Right. Since the test case is reproducible, I suggest to measure the time to load the file and then by subtraction trying to understand whether it's loading or displaying it. That's even better.

**Comment by hellais** [comment]
Yes we need measure actually what is causing the big load by benchmarking each function call runtime leading up to displaying the measurement in the UI.

**Comment by hellais** [comment]
What happened of this issue?

**Comment by lorenzoPrimi** [comment]
That I don't know how to solve it and there hasn't been any valuable input until now.
We need to test if the json downloaded from the explorer has the same problem.

@bassosimone can't we just save a smaller json?

**Comment by bassosimone** [comment]
@lorenzoPrimi sure, but that means dropping data, or storing the body in some other way.

**Comment by lorenzoPrimi** [comment]
This cannot be evaluated until a solution is proposed

**Comment by lorenzoPrimi** [comment]
In Android opening the json file fails with this reason:
`
2019-12-24 11:06:59.648 14135-14135/org.openobservatory.ooniprobe W/System.err: Caused by: android.os.TransactionTooLargeException: data parcel size 2894948 bytes
2019-12-24 11:06:59.648 14135-14135/org.openobservatory.ooniprobe W/System.err:     at android.os.BinderProxy.transactNative(Native Method)
2019-12-24 11:06:59.648 14135-14135/org.openobservatory.ooniprobe W/System.err:     at android.os.BinderProxy.transact(Binder.java:1127)
2019-12-24 11:06:59.648 14135-14135/org.openobservatory.ooniprobe W/System.err:     at android.app.IActivityManager$Stub$Proxy.startActivity(IActivityManager.java:3754)
2019-12-24 11:06:59.648 14135-14135/org.openobservatory.ooniprobe W/System.err:     at android.app.Instrumentation.execStartActivity(Instrumentation.java:1669)
`

**Comment by lorenzoPrimi** [comment]
The failing line is 
```FileUtils.readFileToString(entryFile, Charset.forName("UTF-8"));```
Same to what happens in https://github.com/ooni/probe-android/issues/229

**Comment by lorenzoPrimi** [comment]
@bassosimone what are your thoughts on this?

**Comment by lorenzoPrimi** [comment]
I believe we shouldn't overload the phones by showing so much amount of data, especially as we tried to keep everything compatible with old Android phones who has no memory.

**Comment by hellais** [comment]
> I believe we shouldn't overload the phones by showing so much amount of data, especially as we tried to keep everything compatible with old Android phones who has no memory.

We are talking about a measurement file which is 1.3 MB in size. This is not a lot of data and it should be possible to handle it even in the most low end phone.

Just for context, the Alcatel 1X, which costs new 79 EUR, has 1 GB of memory.

I think more work needs to go into actually determining the root cause of the issue, because it should be possible to load and display a 1.3 MB JSON file on ANY phone from the last decade.

**Comment by lorenzoPrimi** [comment]
Ok I will inspect that `TransactionTooLargeException` to understand the  problem

**Comment by bassosimone** [comment]
> @bassosimone what are your thoughts on this?

We should at least make sure that the exception is not lost and we should display in the view that we could not open the specified file because it is too large.

@lorenzoPrimi how do you reproduce the problem?

**Comment by lorenzoPrimi** [comment]
The discussion for this is happening on https://github.com/ooni/probe/issues/914 as their root is basically the same issue

**Comment by hellais** [comment]
This has been solved in the same way as: https://github.com/ooni/probe/issues/914#issuecomment-575661397
