### ISSUE TITLE
Make Quiz answer options gray in onboarding

### ISSUE THREAD

**Issue by agrabeli** [ooni/probe#871]
A community member mentioned that by having the options "True" and "False" as green and red in the onboarding quiz of the apps, we are indirectly telling users what the correct answer is, without necessarily requesting them to think about the information and question asked.

They therefore propose that we change the colours of the answers in the onboarding quiz to gray, so that they're more neutral (and to improve how we acquire user consent as part of the quiz).

**Comment by hellais** [comment]
The fact that the direction of the correct answer changes (from right to left) on the screen creates already the additional thing that the user needs to think about it.

It is by design easy to answer and the colors are meant to help the user come to the right conclusion. We are not trying to build a real exam of knowledge, but provide education to the user more than just having to tap "next", "next", "next", "done".

As a matter of fact when you get the answer wrong you can still skip it by just tapping continue, yet we explain when you get it wrong the reason.

In my opinion, and based on the consultations we have received from lawyers and designers, our approach is pretty solid and reasonable.

Changes the colors also introduces additional problems from the UI perspective.

**Comment by agrabeli** [comment]
@hellais Fair enough. Thanks for the clarification.
