### ISSUE TITLE
What to do if IP lookup fails?

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#879]
Manually migrated from https://github.com/measurement-kit/measurement-kit/issues/1818

What should we do if IP discover fails? Specifically, what should we do if IP discover fails and the user has configured OONI to scrub its IP from results? We currently continue the test, but we have a theory according to which it may be that in ~100 cases out of ~10M this leads to the IP address not being correctly sanitised. If looking into the data confirms this theory, then maybe we can change our code to attempt to gather the IP address from more sources (e.g. the bouncer when we're using https) as well as to retry if gathering it fails. With respect to the latter point, continuing with refactoring MK as described in [#1666](https://github.com/measurement-kit/measurement-kit/issues/1666) will give us this extra robustness property, because mkcurl retries three times by default in case of connect and/or DNS failure.

**Comment by bassosimone** [comment]
This is priority/high for me because I'd like to avoid keeping this issue in the icebox. The effort may well be much smaller than L, if we do something quick and reasonable rather than second guessing :crossed_fingers:.

**Comment by hellais** [comment]
We have discussed this and have come to the conclusion that if we are not able to determine the country and network of the measurement, because the IP lookup has failed, we should not be running the measurement at all as it's not useful to us.

When we have other ways that don't rely on the network to determine the country we may decide to make the logic behave differently, but until then the recommended solution to this matter is to just stop running the test and mark it as failed.

Put otherwise, measurements with`probe_cc: ZZ` and `probe_asn: AS0` are useless to us.

**Comment by bassosimone** [comment]
What needs to be done at this point, is creating issues for the proper repositories. This is a small interrupt that I will take care of as part of this sprint.

**Comment by bassosimone** [comment]
Done!
