### ISSUE TITLE
Discover when OONI backend infrastructure is being blocked

### ISSUE THREAD

**Issue by hellais** [ooni/probe#886]
Discover when OONI backend infrastructure is being blocked in a particular country or network based on OONI Probe tests and [Pipeline analysis](https://github.com/ooni/pipeline/issues/238).

* [ ] Add a custom annotation which specifies the method used for uploading measurements
* [ ] Evaluate the possibility of recording performance metrics pertaining to the availability of our infrastructure

**Comment by hellais** [comment]
When we are speaking to our infrastructure we should have a set of fallback strategies (ex. use psiphon) and then we need to report back that we could not communicate and what failed.

We should be sure to use things like firebase that provide collateral to know what failed.

**Comment by bassosimone** [comment]
Transferring some effort to https://github.com/ooni/probe-engine/issues/614. In yesterday's backend meeting, we discussed attempting to use backend metrics as much as possible to do that. Thus it makes sense to scale down my involvement here. To keep in mind:

- [ ] we want to understand what happens when we submit normally
- [ ] when we submit using cloudfronted
- [ ] when we submit using tor and onion
- [ ] we probably want an issue regarding having specific domains for, e.g., when using Tor
- [ ] we probably want an issue regarding Psiphon depending on probe-services

The idea here is to understand what works, what is missing, and help planning.

**Comment by bassosimone** [comment]
I did everything that was listed in https://github.com/ooni/probe/issues/886#issuecomment-638474684 and wrote down what I learned as a comment in https://github.com/ooni/backend/issues/417#issuecomment-638811201.
