### ISSUE TITLE
Support submitting results of measurements using circumvention tools

### ISSUE THREAD

**Issue by hellais** [ooni/probe#888]
This will likely require the creation of sub-issues for probe-engine & probe-desktop & mobile.

* [ ] Submit using Psiphon
* [ ] Evaluate if we should submit via Tor
* [ ] Try with DoH or DoT

**Comment by bassosimone** [comment]
This is done. Probe-engine supports setting an external socks5 proxy and I have already used it a number of times to perform and submit measurements. What's more, the engine.Session has support for starting an on-demand Psiphon tunnel. So, what is missing here is the logic such that, if we cannot submit a measurement using normal channels, then we fallback to Psiphon. This is out of the scope of this issue. To conclude, we can close this issue because we support doing that.

This was done in Sprint 11 and 12 though all the refactoring work performed in netx. The main related issues are most certainly https://github.com/ooni/probe-engine/issues/509 and https://github.com/ooni/probe-engine/issues/543.
