### ISSUE TITLE
hero section has a shadow in Test Overview screens.

### ISSUE THREAD

**Issue by elioqoshi** [ooni/probe#907]
There is a slight shadow underneath the hero section on test overview screens. I think it should be removed.

![image](https://user-images.githubusercontent.com/5436686/53729654-0d32b200-3e76-11e9-80a9-f01e26b401fe.png)

**Comment by hellais** [comment]
I don't agree with @elioqoshi that the shadow should be removed.

Let me also further explain the reason why.

One of the core concepts in material design is that the graphical elements reflect their physical meat-space equivalent. An important aspect is that of how surfaces are elevated differently to convey how the interact with each other.

For example a button will be elevated compared to the page it's on, because it's a thing you can press down.

So to get to the reason why the shadow is needed here, the reason is very simple, the hero unit is on an elevated plane compared to the text content. This can be seen by the fact that you can scroll the text and it will go "under" the hero unit.
As such we need to convey the fact that the hero unit is elevated and the way to do it in the material design language is through a drop shadow.

I say we close this as wontfix.
