### ISSUE TITLE
view log in new tests doesn't work.

### ISSUE THREAD

**Issue by xhdix** [ooni/probe#914]
The `View Log` doesn't work in new tests in the `web connectivity` section. (About two days)

- There is no problem with old tests. 

- I could not get more information.

- Version: 2.0.3 <--> 2.1.0-beta.4

**Comment by lorenzoPrimi** [comment]
I don't think that a webview with `text/plain` that can read only file from the app storage (that is chrooted) can be injected with code, expecially because we use it to read a text file (the log)
One solution to harden the webview, I know  it's possible to restrict the domains the webview can connect to, in this case will be empty array.

The react solution is how I would like to see this implemented in the future.

**Comment by lorenzoPrimi** [comment]
This is all I found about how to implement a safe webview. Still no luck on any alternative.
https://www.praetorian.com/blog/how-to-identify-and-prevent-uiwebview-cross-site-scripting-xss

`
In addition, make use of the UIWebViewDelegate protocol to implement a whitelist of safe domains to load content from or implement your set of classes to handle the complex problem of whitelisting.
`

**Comment by xhdix** [comment]
We do not know what is the output of each site, and what are the solutions for bypassing, or what kind of attacks can be made that are not yet publicly available but can be used by governments to control users' devices.
The truth is that a solution is safe as long as the bypass is not public.
So my strong suggestion is: Don't parse the received HTML content.
https://www.ptsecurity.com/ww-en/about/news/high-risk-vulnerability-in-android-devices-discovered-by-positive-technologies/

**Comment by bassosimone** [comment]
@lorenzoPrimi I believe we should learn how to implement a smart text view ourselves rather than trying to secure a web view. Another issue with securing web views is that many devices are not using the latest version, either because users do not update, or because vendors do not update. Do we have the same issues if we use, say, an EditText with editing disabled?

**Comment by lorenzoPrimi** [comment]
Creating a custom `TextView` and make it  better than the apple one it would be 10 times more complicated than implementing this view in react, that is the final result we want to achieve, to have a nice json browser to expand and collapse keys.
So for now we need to think something smarter and so far I don't see many options:
- Secure WebView, maybe the new `MKWebView` of Apple
- Leave it as it is and add a loading wheel
- Go straight the react way

**Comment by hellais** [comment]
> Creating a custom TextView and make it better than the apple one

I would say that we should prioritise a solution for android (most of our users are there) and I am OK with us accepting a hackish (yet secure) solution on iOS (for example the spinner wheel), since we don't have as many users there.

@lorenzoPrimi how about we start off by trying to do a custom TextView on **Android**, using some of the above snippets of code and see how that goes? The incremental loading option seems pretty promising to me: https://github.com/YablokovDmitry/FileView/blob/master/sample/src/main/java/com/ydn/fileviewsample/MainActivity.kt.

Or as @bassosimone is suggesting trying out first if EditText still presents the same issues.

**Comment by lorenzoPrimi** [comment]
@hellais I can try but as I said the incremental load solves only the problem of the loading time, not the extremely slow textview when scrolling after is fully loaded.

**Comment by lorenzoPrimi** [comment]
The discussion for this issue is happening on https://github.com/ooni/probe/issues/865 their root is basically the same issue

**Comment by lorenzoPrimi** [comment]
Some tests and considerations:
- `EditText` didn't work
- Loading a long log takes around 15 seconds on emulator at the moment
- Spinning wheel won't work as there is no callback from TextView saying "I finished loading" it's only on webview
- The current `TextView` doesn't lag once is loaded
- The problem of long loading is due to the scrollview that have to "calculate" the height of the view***

This brings us to my solution:
- Loading just the first X lines/bytes of text and when you scroll to the bottom of the log will load more

This*** could add a problem:
- The ScrollView will have to recalculate his height

I will implement this and then report back on how it works on Android

**Comment by bassosimone** [comment]
@lorenzoPrimi this is very promising, thank you!

**Comment by lorenzoPrimi** [comment]
For me it's gonna be a big hole in the water.
Wow now you are the optimist and I'm the pessimist!

**Comment by hellais** [comment]
In the end we went for just disabling hardware accelleration on Android.

On iOS we just put a loading string.

See: https://github.com/ooni/probe-android/pull/282 & https://github.com/ooni/probe-ios/pull/328
