### ISSUE TITLE
ooniprobe bypasses device-level VPN settings on iOS

### ISSUE THREAD

**Issue by hellais** [ooni/probe#921]
A user reported that on iOS ooniprobe will bypass device-level VPN settings.

This seems to not be happening on Android. I am unsure if this is to be considered a bug or a feature actually (since we prefer to not be testing over a VPN), but we should probably be aware of this and maybe inform the user that we are going to be bypass the VPN if we have the power to do this.

**Comment by bassosimone** [comment]
I will do this now as part of our efforts regarding testing. I think we should mention in our documentation what happens if there's a VPN and, before that, check what happens on mobile devices.

**Comment by bassosimone** [comment]
I have manually verified that with Psiphon installed and running on Android:

![Screenshot_2020-04-29-13-24-57](https://user-images.githubusercontent.com/337298/80591018-3cfb2c80-8a1d-11ea-8905-fe8f7eb99cfd.jpg)

and on iOS:

![IMG_0709](https://user-images.githubusercontent.com/337298/80591179-83e92200-8a1d-11ea-8efa-be042220619c.jpg)

the code was using the VPN. So, it seems to me that, if there a VPN running system wide, we are using it, which maybe is not what we want, but at least it's not surprising. (With the Go engine we _could_ allow the user to specify a SOCKS5 proxy to use, but I think this amount of manual configuration is perhaps too geeky, and could possibly break stuff?)

In any case, I don't consider this an issue, since it seems to me we should limit ourselves to honor the VPN configured using system settings, which I've just verified that we do.
