### ISSUE TITLE
Consistency in handing _is_beta in config.json

### ISSUE THREAD

**Issue by sarathms** [ooni/probe#960]
> We may want to keep this and add some extra logic to do some cleanup if we notice the `_is_beta` key inside of the config file.
> 
> This is mostly for some possible inconsistencies between the `probe-cli` version of the beta and what we are going to be shipping in the stable release.
> 
> @bassosimone may have some thoughts about this.
> 
> If this is not necessary we can just drop it directly, but let's also remember to drop that key from the config file.

Ref: https://github.com/ooni/probe-desktop/pull/77#discussion_r341458515

**Comment by hellais** [comment]
I looked at this and it seems like we aren't setting the `_is_beta` flag anymore since https://github.com/ooni/probe-cli/commit/8a27de6c.

I thought a bit more about this and I think that what makes the most sense to do prior to the stable release is to change the default system path for the configuration of OONI Probe 3.0.0 from the current `~/.ooni/` to `~/.ooniprobe`.

This also solves the current problem with the ooniprobe 2.0 installation conflicting with ooniprobe 3.0 and it would allow us to get rid of all this annoying migration code: https://github.com/ooni/probe-cli/blob/master/internal/legacy/legacy.go.

@bassosimone @sarathms what do you think?

**Comment by bassosimone** [comment]
Yes, please!

**Comment by hellais** [comment]
Great thanks. I filed this as a new issues. Closing.
