### ISSUE TITLE
engine, cli, desktop, mobile: proxy to speak with the backend

### ISSUE THREAD

**Issue by hellais** [ooni/probe#985]
It was brought up during the weekly meeting the need to add the capability for users to configure OONI Probe to use a proxy when speaking to backend services to deal with blocking.

**Comment by bassosimone** [comment]
Here's my view on this topic:

1. `miniooni` users are advanced users and have full control (`--proxy` to use any proxy, `--tunnel psiphon` to start a psiphon tunnel when https://github.com/ooni/probe-engine/issues/586 is done, `--tunnel tor` and `--tor-binary` and `--tor-args` to run a `tor` binary with the desired pluggable transports)

2. `ooniprobe` users will have automatic fallback to psiphon when https://github.com/ooni/probe-engine/issues/586 is done

According to me, this is a good compromise between automatic fallbacks and usability.

**Comment by bassosimone** [comment]
We probably need to rework a little bit the code for selecting a proxy. We also need to (1) ensure that we can use a proxy from mobile devices via the currently exposed API and (2) that we proxy what we should and don't proxy what we should not. (While this seems obvious, and while the code probably does the right thing, it's worth it to double check and perhaps write some tests.)

**Comment by bassosimone** [comment]
Okay, when https://github.com/ooni/probe-cli/pull/301 is merged, we are well positioned to start testing on mobile.

**Comment by bassosimone** [comment]
I've noticed that when we're using a proxy we skip the resolver identification, but this is actually not the desired outcome. We want to record it, because it provides value to measurements. I suppose skipping it was an argument when I was planning to run measurements over a proxy. Now, that codebase evolved in a completely different way. It provides a proxy for contacting the OONI backend. So the original reason to omit information about the system resolver is now void.

**Comment by bassosimone** [comment]
This was actually XL

**Comment by bassosimone** [comment]
Will continue this work in the next Sprint.

**Comment by bassosimone** [comment]
Here's an alpha release where we support the psiphon proxy: https://github.com/ooni/probe-cli/releases/tag/v3.10.0-alpha. We still need to write down a reasonable and accurate changelog for that. We're also working to publish a prototype branch for Android,

**Comment by bassosimone** [comment]
We have a prototype of this functionality for Android (see https://github.com/ooni/probe-android/pull/423). Here are the related screenshots. Many thanks to @lorenzoPrimi for quickly helping out to improve the settings.

The first change is that we create a specific submenu for controlling whether OONI should use a proxy when speaking to its backends and other services required for controlling the probe:

![photo6050828241494717933](https://user-images.githubusercontent.com/337298/115350919-f8c8e500-a1b5-11eb-902d-89ffbcaa68d0.jpg)

The second change defines the content of such a section. What we want to obtain is (morally) a radio where we can choose between "none", "psiphon", and a custom proxy URL. What we have for now is a bit far from that ideal:

![photo6050828241494717932](https://user-images.githubusercontent.com/337298/115351101-2ada4700-a1b6-11eb-8b36-d33a37ab9009.jpg)

There are some technical difficulties in doing this on Android. My main issue with the current design is that it's not obvious for a user how to use the custom proxy URL. It's not very clear that this is a textual field. It's not known in advance what is the content that the user should put in there (something like `socks5://127.0.0.1:9050` when using Orbot).

So, I suppose we need to continue iterating over this initial design. (But, if we omit the custom proxy part, this design is probably good enough to start shipping a Psiphon proxy to users?)

**Comment by bassosimone** [comment]
Among the things that we still need to do: writing tests for the proxy functionality for the mobile probes. (The current situation where we have three slightly different code paths for running tests in `miniooni`, CLI, and mobile is draining and we should do something about it.)

**Comment by bassosimone** [comment]
I suppose this issue could either generate a bunch of child issues (for `cli`, `mobile`, `ux` etc.) or continue as a long running issue and double its total effort. It has been running for quite some time now and has been quite a hill to take.

**Comment by hellais** [comment]
Thanks for working on this!

Some feedback on some improvements that can be made to the UX:
1. I think this option should be listed above the advanced settings right after the Privacy settings
2. I would suggest using instead of two switches, I would suggest using radio buttons with 3 available options: "none", "Psiphon" and "Custom Proxy" (see: https://material.io/components/radio-buttons#specs). Only when the user selects the "Custom Proxy" option will the textbox appear for inputting a custom proxy address. We can also add some text below explaining the format and provide an example of how the proxy address should look like in the case of orbot.

**Comment by sarathms** [comment]
> Only when the user selects the "Custom Proxy" option will the textbox appear for inputting a custom proxy address.

It might be useful to have the custom input section always visible under the 'Custom Proxy' radio option but disabled, unless the  radio is selected.

If it isn't too difficult, it would be cool to show if any proxy is already enabled at the top level settings screen itself. Like how Telegram Desktop does it here: 
![image](https://user-images.githubusercontent.com/700829/115376460-b7780b80-a19c-11eb-963f-0a81aea6c062.png)

**Comment by agrabeli** [comment]
@bassosimone @lorenzoPrimi thanks for working on this! Exciting to see how close we are to supporting circumvention for OONI Probe! :)

Upon looking at the screenshots, my feedback was basically the same as that of @hellais. I agree that the `OONI backend proxy` setting should probably be listed before the `Advanced` setting (I would have normally assumed that this would go inside `Advanced`, but since the proxy setting has many settings of its own, I can see why it makes sense to have it as a separate setting). While I would have preferred switches to ensure UI consistency with the rest of the app, I can see why radio buttons (as proposed by @hellais) are preferable in this case, where we want to ensure that users only select 1 option. I also agree that we should probably explain "custom proxy" and provide an example (particularly for Orbot). 

Perhaps at the end of the settings, we can also **include a string where we explain what these settings are about**?

For example, we could include something like the following string:

`Are you unable to use OONI Probe? Try enabling the use of Psiphon (https://psiphon.ca/) for potential censorship circumvention. Alternatively, you can use a custom proxy.`

@bassosimone @lorenzoPrimi what will the default settings be? Will `Use Psiphon` be enabled by default? Or will all options be disabled by default?

**Comment by bassosimone** [comment]
We've done a bunch of work to have a proxy in the next release. I've been dragging this issue for too many Sprints now. Time to close and to collect some points. We will continue the work in https://github.com/ooni/probe/issues/1469.

**Comment by besendorf** [comment]
Sorry to comment on an old issue but there is no gui to configure a proxy for ooni-desktop ist there?
