### ISSUE TITLE
discuss: use cell tower information as primary geolocation signal

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#991]
I want to make sure we don't forget about this opportunity. As mentioned by @fortuna in the `#ooni` slack channel: "the Mobile Country Code and the Mobile Network Code from the SIM card [...] do not require extra permissions [...] On Android, we can use the TelephonyManager API to collect that information. On iOS there's CTCarrier." Ideally we can discuss this in a dev meeting in this sprint?

**Comment by fortuna** [comment]
IP-based geolocation can be far from 100% precision in some locations. If you have a lot of data in locations with lower precision, the misclassified data can contaminate and overwhelm locations with less data. It's important to be as close to 100% as possible.

To address the issue on mobile phones, we propose to collect the [Mobile Country Code](https://en.wikipedia.org/wiki/Mobile_country_code) and Mobile Network Code for both the SIM card provider and the network the user is connected to. This will provide us not only a new, independent source of location information, but also the user's carrier.

Having self-reported country and carrier information is a lot more precise, but it's unclear what the coverage is. Data from the [Intra app](https://getintra.org) shows that the connected network may be available even if the user is on Wi-Fi, likely due to the fact that the user may still be connected to the cell network for telephony services.

The connected network location is a great proxy for the user’s physical location, since that represents the local network they are connected to, even if their SIM card is from a different country.

Having the information for both the connected network and sim provider can allow us to uncover roaming cases and how it affects censorship.

On Android, we can use the [TelephonyManager API](https://developer.android.com/reference/android/telephony/TelephonyManager#getNetworkCountryIso()) to collect that information. On iOS there's [CTCarrier](https://developer.apple.com/documentation/coretelephony/ctcarrier).

**Comment by hellais** [comment]
As next steps:
* Come up with details of what information we are planning to include in OONI probe test results and what is the scope of it
* Look into what happens when a phone is in roaming, if the MCC is updated MNC
* Bring up this topic during one of the OONI community meetings and see how the OONI community feels about this

**Comment by bassosimone** [comment]
I am going to create follow-up issues and close this PR.

**Comment by bassosimone** [comment]
Here's the list of follow-up issues:

* https://github.com/ooni/probe/issues/1014

* https://github.com/ooni/probe/issues/1015

* https://github.com/ooni/ooni.org/issues/389

* https://github.com/ooni/probe-engine/issues/337
